// pos-client/src/views/AccountStatement.jsx
import React, { useState, useEffect } from 'react';
import { api, msg } from '../services';
import { SafeFontAwesomeIcon, Loader, SystemButton } from '../components';
import { faFilePdf, faFileCsv, faPrint, faSearch, faUndo } from '@fortawesome/free-solid-svg-icons';
import Select from 'react-select';
import { useLocation } from 'react-router-dom';

const AccountStatement = () => {
  const location = useLocation();
  const [loading, setLoading] = useState(false);
  const [accounts, setAccounts] = useState([]);
  const [selectedAccount, setSelectedAccount] = useState(null);
  const [startDate, setStartDate] = useState(new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().split('T')[0]);
  const [endDate, setEndDate] = useState(new Date().toISOString().split('T')[0]);
  const [type, setType] = useState('0'); // 0: All, 1: Debit, 2: Credit
  const [statementData, setStatementData] = useState(null);

  // For accounts selection
  useEffect(() => {
    const loadAccountsDirectly = async () => {
        try {
            const response = await api.get('accounts'); 
            if (response.status == 200 && response.data.status == 200 && Array.isArray(response.data.data)) {
                const options = response.data.data.map(acc => ({
                    value: acc.id,
                    label: `${acc.name} [${acc.account_no}]`
                }));
                setAccounts(options);
                
                // If passed via navigation state
                if (location.state && location.state.account_id) {
                    const passedAcc = options.find(acc => acc.value === location.state.account_id);
                    if (passedAcc) {
                        setSelectedAccount(passedAcc);
                        return;
                    }
                }

                // Set default account if available
                const defaultAcc = response.data.data.find(acc => acc.is_default);
                if (defaultAcc) {
                    setSelectedAccount({
                        value: defaultAcc.id,
                        label: `${defaultAcc.name} [${defaultAcc.account_no}]`
                    });
                }
            }
        } catch (e) {
            console.error(e);
        }
    };
    loadAccountsDirectly();
  }, [location.state]);

  useEffect(() => {
    if (selectedAccount) {
        fetchStatement();
    }
  }, [selectedAccount, startDate, endDate, type]);

  const fetchStatement = async () => {
    if (!selectedAccount) {
      msg.error('Please select an account');
      return;
    }
    setLoading(true);
    try {
      const payload = {
        account_id: selectedAccount.value,
        start_date: startDate,
        end_date: endDate,
        type: type
      };
      const response = await api.post('account-statement').values(payload);
      if (response.status == 200 && response.data.status == 200) {
        setStatementData(response.data);
      } else {
        msg.error(response.data?.message || 'Failed to fetch account statement');
      }
    } catch (error) {
      msg.error('Failed to fetch account statement');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleExportCSV = () => {
    if (!statementData || !statementData.transactions.length) return;
    
    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Date,Reference No,Related Transaction,Credit,Debit,Balance\n";
    
    statementData.transactions.forEach(row => {
      csvContent += `${row.date},${row.reference_no},${row.transaction_ref},${row.credit},${row.debit},${row.balance}\n`;
    });

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `account_statement_${selectedAccount.label}.csv`);
    document.body.appendChild(link);
    link.click();
  };

  return (
    <div className="container-fluid py-4">
      <div className="card shadow-sm border-0 mb-4">
        <div className="card-header bg-white border-0 py-3">
          <div className="row align-items-center">
            <div className="col">
              <h3 className="mb-0 text-primary font-weight-bold">Account Statement</h3>
            </div>
            <div className="col-auto">
              <div className="btn-group shadow-sm">
                <button className="btn btn-outline-secondary btn-sm" onClick={handleExportCSV}>
                  <SafeFontAwesomeIcon icon={faFileCsv} className="mr-2" /> CSV
                </button>
                <button className="btn btn-outline-secondary btn-sm" onClick={() => msg.info('PDF Export coming soon')}>
                  <SafeFontAwesomeIcon icon={faFilePdf} className="mr-2" /> PDF
                </button>
                <button className="btn btn-primary btn-sm" onClick={handlePrint}>
                  <SafeFontAwesomeIcon icon={faPrint} className="mr-2" /> Print
                </button>
              </div>
            </div>
          </div>
        </div>
        
        <div className="card-body bg-light-50">
          <div className="row g-3">
            <div className="col-md-3">
              <label className="small font-weight-bold text-muted uppercase">Select Account</label>
              <Select
                options={accounts}
                value={selectedAccount}
                onChange={setSelectedAccount}
                placeholder="Choose account..."
                className="react-select-container"
                classNamePrefix="react-select"
              />
            </div>
            <div className="col-md-3">
              <label className="small font-weight-bold text-muted uppercase">Start Date</label>
              <input 
                type="date" 
                className="form-control form-control-sm" 
                value={startDate} 
                onChange={(e) => setStartDate(e.target.value)} 
              />
            </div>
            <div className="col-md-3">
              <label className="small font-weight-bold text-muted uppercase">End Date</label>
              <input 
                type="date" 
                className="form-control form-control-sm" 
                value={endDate} 
                onChange={(e) => setEndDate(e.target.value)} 
              />
            </div>
            <div className="col-md-2">
              <label className="small font-weight-bold text-muted uppercase">Type</label>
              <select 
                className="form-control form-control-sm" 
                value={type} 
                onChange={(e) => setType(e.target.value)}
              >
                <option value="0">All Transactions</option>
                <option value="2">Credit Only</option>
                <option value="1">Debit Only</option>
              </select>
            </div>
            <div className="col-md-1 d-flex align-items-end">
              <button className="btn btn-info btn-sm btn-block" onClick={fetchStatement}>
                <SafeFontAwesomeIcon icon={faSearch} />
              </button>
            </div>
          </div>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-5">
          <Loader />
          <p className="mt-2 text-muted">Calculating transactions...</p>
        </div>
      ) : (
        statementData && (
          <div className="card shadow-sm border-0 animated fadeIn">
            <div className="card-header bg-white border-0 py-3">
               <div className="d-flex justify-content-between align-items-center text-muted small">
                  <div>
                     <strong>Account:</strong> {statementData.account.name} [{statementData.account.account_no}]
                  </div>
                  <div>
                     <strong>Initial Balance:</strong> {Number(statementData.initial_balance.initial_balance).toLocaleString(undefined, {minimumFractionDigits: 2})}
                  </div>
               </div>
            </div>
            <div className="table-responsive">
              <table className="table table-hover table-striped mb-0">
                <thead className="thead-light">
                  <tr>
                    <th className="border-0">#</th>
                    <th className="border-0">Date</th>
                    <th className="border-0">Reference No</th>
                    <th className="border-0">Related Transaction</th>
                    <th className="border-0 text-right">Credit</th>
                    <th className="border-0 text-right">Debit</th>
                    <th className="border-0 text-right">Balance</th>
                  </tr>
                </thead>
                <tbody>
                  {statementData.transactions.length > 0 ? (
                    statementData.transactions.map((row, index) => (
                      <tr key={index}>
                        <td>{statementData.transactions.length - index}</td>
                        <td>{new Date(row.date).toLocaleDateString()}</td>
                        <td><span className="badge badge-light border">{row.reference_no}</span></td>
                        <td>{row.transaction_ref || '---'}</td>
                        <td className="text-right text-success font-weight-bold">
                          {row.credit > 0 ? Number(row.credit).toLocaleString(undefined, {minimumFractionDigits: 2}) : '0.00'}
                        </td>
                        <td className="text-right text-danger font-weight-bold">
                          {row.debit > 0 ? Number(row.debit).toLocaleString(undefined, {minimumFractionDigits: 2}) : '0.00'}
                        </td>
                        <td className="text-right font-weight-bold bg-light-50">
                          {Number(row.balance).toLocaleString(undefined, {minimumFractionDigits: 2})}
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan="7" className="text-center py-4 text-muted">No transactions found for the selected period.</td>
                    </tr>
                  )}
                  
                  {/* Initial Balance Row (as per Blade logic if empty or at the end) */}
                  <tr>
                    <td>-</td>
                    <td>{new Date(statementData.initial_balance.created_at).toLocaleDateString()}</td>
                    <td><span className="font-weight-bold">Initial Balance</span></td>
                    <td>------</td>
                    <td className="text-right font-weight-bold">{Number(statementData.initial_balance.initial_balance).toLocaleString(undefined, {minimumFractionDigits: 2})}</td>
                    <td className="text-right font-weight-bold">0.00</td>
                    <td className="text-right font-weight-bold bg-light-50">{Number(statementData.initial_balance.initial_balance).toLocaleString(undefined, {minimumFractionDigits: 2})}</td>
                  </tr>
                </tbody>
                <tfoot className="bg-light">
                    <tr>
                        <th colSpan="4" className="text-right">Total Balance</th>
                        <th colSpan="3" className="text-right text-primary h5 mb-0">
                            {Number(statementData.total_balance).toLocaleString(undefined, {minimumFractionDigits: 2})}
                        </th>
                    </tr>
                </tfoot>
              </table>
            </div>
          </div>
        )
      )}
      
      <style>{`
        .bg-light-50 { background-color: rgba(0,0,0,0.02); }
        .animated { animation-duration: 0.5s; animation-fill-mode: both; }
        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
        .fadeIn { animation-name: fadeIn; }
        .react-select-container .react-select__control {
            border-color: #ced4da;
            border-radius: 0.2rem;
            min-height: 31px;
            height: 31px;
        }
        .react-select-container .react-select__value-container {
            padding: 0 8px;
        }
        .react-select-container .react-select__indicators {
            height: 29px;
        }
        @media print {
            .card-header, .card-body { border: none !important; box-shadow: none !important; }
            .btn, label, select, input, .col-auto, .btn-group { display: none !important; }
            body { padding: 0 !important; }
            .container-fluid { width: 100% !important; padding: 0 !important; }
            .table { border-collapse: collapse !important; }
            .table-striped tbody tr:nth-of-type(odd) { background-color: rgba(0,0,0,.05) !important; }
        }
      `}</style>
    </div>
  );
};

export default AccountStatement;

// pos-client - Copy/src/views/pages/accounting/account-statement.vue
<script setup>
import api from '@/service/api';
import { useToast } from 'primevue/usetoast';
import { onMounted, ref, computed } from 'vue';
import { useRoute } from 'vue-router';

const toast = useToast();
const route = useRoute();

const accounts = ref([]);
const filters = ref({
    accountId: null,
    type: '0',
    startDate: null,
    endDate: null
});
const loading = ref(false);
const optionsLoading = ref(true);
const transactions = ref([]);
const totals = ref({ credit: 0, debit: 0, closing_balance: 0 });
const accountInfo = ref(null);

const typeOptions = [
    { label: 'All Transactions', value: '0' },
    { label: 'Debit Only', value: '1' },
    { label: 'Credit Only', value: '2' }
];

function defaultStartDate() {
    const today = new Date();
    return new Date(today.getFullYear(), today.getMonth(), 1);
}

function defaultEndDate() {
    return new Date();
}

function parseQueryDate(value, fallback) {
    if (!value) return fallback;
    const parsed = new Date(value);
    return Number.isNaN(parsed.getTime()) ? fallback : parsed;
}

onMounted(async () => {
    filters.value.startDate = parseQueryDate(route.query.startDate, defaultStartDate());
    filters.value.endDate = parseQueryDate(route.query.endDate, defaultEndDate());
    filters.value.accountId = route.query.accountId ? Number(route.query.accountId) : null;
    filters.value.type = route.query.type ? String(route.query.type) : '0';

    await loadOptions();
    if (filters.value.accountId) {
        await fetchStatement();
    }
});

function formatCurrency(value) {
    const number = Number(value || 0);
    return number.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function formatDateDisplay(value) {
    if (!value) return '—';
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return value;
    return date.toLocaleString();
}

function formatDateForApi(date) {
    if (!(date instanceof Date)) return null;
    const iso = date.toISOString();
    return iso.slice(0, 10);
}

async function loadOptions() {
    optionsLoading.value = true;
    try {
        const res = await api.get('accounts/options');
        if (res.error) {
            const msg = res.error?.response?.data?.message || 'Failed to load account options';
            toast.add({ severity: 'error', summary: 'Error', detail: msg, life: 3000 });
            accounts.value = [];
            return;
        }
        if (res.data?.status === 200) {
            accounts.value = res.data.data || [];
            if (!filters.value.accountId && accounts.value.length) {
                const defaultAccount = accounts.value.find((acc) => acc.is_default) || accounts.value[0];
                filters.value.accountId = defaultAccount.id;
            }
        }
    } catch (error) {
        toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to load account options', life: 3000 });
    } finally {
        optionsLoading.value = false;
    }
}

async function fetchStatement() {
    if (!filters.value.accountId) {
        toast.add({ severity: 'warn', summary: 'Validation', detail: 'Select an account first', life: 3000 });
        return;
    }
    if (!filters.value.startDate || !filters.value.endDate) {
        toast.add({ severity: 'warn', summary: 'Validation', detail: 'Select a valid date range', life: 3000 });
        return;
    }

    loading.value = true;
    try {
        const params = new URLSearchParams({
            account_id: String(filters.value.accountId),
            start_date: formatDateForApi(filters.value.startDate),
            end_date: formatDateForApi(filters.value.endDate),
            type: filters.value.type || '0'
        });

        const res = await api.get(`accounts/statement?${params.toString()}`);
        if (res.error) {
            const msg = res.error?.response?.data?.message || 'Failed to load account statement';
            toast.add({ severity: 'error', summary: 'Error', detail: msg, life: 3000 });
            return;
        }

        if (res.data?.status === 200) {
            const data = res.data.data || {};
            accountInfo.value = data.account || null;
            totals.value = data.totals || { credit: 0, debit: 0, closing_balance: 0 };
            transactions.value = data.transactions || [];
        }
    } catch (error) {
        const msg = error.response?.data?.message || 'Failed to load account statement';
        toast.add({ severity: 'error', summary: 'Error', detail: msg, life: 3000 });
    } finally {
        loading.value = false;
    }
}

const selectedAccountLabel = computed(() => {
    const found = accounts.value.find((acc) => acc.id === filters.value.accountId);
    if (!found) return 'Select account';
    return found.label || `${found.name}${found.account_no ? ` (${found.account_no})` : ''}`;
});
</script>

<template>
    <div class="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-950 p-4 md:p-6 lg:p-8">
        <div class="mb-6 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
            <div>
                <h1 class="text-3xl font-bold text-gray-900 dark:text-gray-100 flex items-center gap-3">
                    <i class="pi pi-book text-primary"></i>
                    Account Statement
                </h1>
                <p class="text-gray-600 dark:text-gray-400 mt-1">Review detailed transactions for a specific account</p>
            </div>
            <div v-if="accountInfo" class="bg-white dark:bg-gray-800 rounded-xl shadow border border-gray-200 dark:border-gray-700 p-4">
                <div class="text-sm text-gray-500 dark:text-gray-400">Account</div>
                <div class="text-lg font-semibold text-gray-900 dark:text-gray-100">
                    {{ accountInfo.name }}
                    <span v-if="accountInfo.account_no" class="text-sm font-normal text-gray-500 dark:text-gray-400">
                        ({{ accountInfo.account_no }})
                    </span>
                </div>
                <div class="mt-1 text-sm text-gray-500 dark:text-gray-400">
                    Initial Balance: <span class="font-semibold text-gray-900 dark:text-gray-100">{{ formatCurrency(accountInfo.initial_balance) }}</span>
                </div>
            </div>
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-2xl shadow border border-gray-200 dark:border-gray-700 p-4 mb-6">
            <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div>
                    <label class="block text-sm font-semibold mb-2">Account</label>
                    <Dropdown
                        v-model="filters.accountId"
                        :options="accounts"
                        optionLabel="label"
                        optionValue="id"
                        class="w-full"
                        :loading="optionsLoading"
                        placeholder="Select account"
                    />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Type</label>
                    <Select v-model="filters.type" :options="typeOptions" optionLabel="label" optionValue="value" class="w-full" />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Start Date</label>
                    <Calendar v-model="filters.startDate" class="w-full" dateFormat="dd-mm-yy" showIcon />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">End Date</label>
                    <Calendar v-model="filters.endDate" class="w-full" dateFormat="dd-mm-yy" showIcon />
                </div>
            </div>
            <div class="mt-4 flex justify-end">
                <Button label="View Statement" icon="pi pi-search" @click="fetchStatement" />
            </div>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
            <div class="bg-white dark:bg-gray-800 rounded-xl shadow border border-gray-200 dark:border-gray-700 p-4">
                <div class="text-sm text-gray-500 dark:text-gray-400">Total Credit</div>
                <div class="text-2xl font-semibold text-emerald-500">{{ formatCurrency(totals.credit) }}</div>
            </div>
            <div class="bg-white dark:bg-gray-800 rounded-xl shadow border border-gray-200 dark:border-gray-700 p-4">
                <div class="text-sm text-gray-500 dark:text-gray-400">Total Debit</div>
                <div class="text-2xl font-semibold text-rose-500">{{ formatCurrency(totals.debit) }}</div>
            </div>
            <div class="bg-white dark:bg-gray-800 rounded-xl shadow border border-gray-200 dark:border-gray-700 p-4">
                <div class="text-sm text-gray-500 dark:text-gray-400">Closing Balance</div>
                <div
                    class="text-2xl font-semibold"
                    :class="totals.closing_balance >= 0 ? 'text-emerald-500' : 'text-rose-500'"
                >
                    {{ formatCurrency(totals.closing_balance) }}
                </div>
            </div>
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700 overflow-hidden">
            <DataTable :value="transactions" :loading="loading" stripedRows tableStyle="min-width: 70rem">
                <template #empty>
                    <div class="text-center py-12 text-gray-500">No transactions for the selected filters</div>
                </template>
                <Column field="date" header="Date" style="min-width: 170px">
                    <template #body="{ data }">
                        {{ formatDateDisplay(data.date) }}
                    </template>
                </Column>
                <Column field="reference" header="Reference" style="min-width: 160px">
                    <template #body="{ data }">{{ data.reference || '—' }}</template>
                </Column>
                <Column field="related_reference" header="Related Transaction" style="min-width: 160px">
                    <template #body="{ data }">{{ data.related_reference || '—' }}</template>
                </Column>
                <Column field="description" header="Description" style="min-width: 200px">
                    <template #body="{ data }">{{ data.description || '—' }}</template>
                </Column>
                <Column field="credit" header="Credit" style="min-width: 120px">
                    <template #body="{ data }">
                        <span class="text-emerald-500 font-semibold">{{ formatCurrency(data.credit) }}</span>
                    </template>
                </Column>
                <Column field="debit" header="Debit" style="min-width: 120px">
                    <template #body="{ data }">
                        <span class="text-rose-500 font-semibold">{{ formatCurrency(data.debit) }}</span>
                    </template>
                </Column>
                <Column field="balance" header="Running Balance" style="min-width: 140px">
                    <template #body="{ data }">
                        <span :class="data.balance >= 0 ? 'text-emerald-500' : 'text-rose-500'">
                            {{ formatCurrency(data.balance) }}
                        </span>
                    </template>
                </Column>
            </DataTable>
        </div>
    </div>
</template>
