// pos-client/src/views/master/PosSetting.jsx
import React, { useState, useEffect } from 'react';
import { api, msg } from '../../services';

const moduleName = 'POS Setting';

const FIXED_PAYMENT_OPTIONS = [
  { value: 'cash', label: 'Cash' },
  { value: 'card', label: 'Card' },
  { value: 'credit', label: 'Credit Sale' },
  { value: 'cheque', label: 'Cheque' },
  { value: 'gift_card', label: 'Gift Card' },
  { value: 'deposit', label: 'Deposit' },
  { value: 'points', label: 'Points' },
  { value: 'razorpay', label: 'Razorpay' },
  { value: 'pesapal', label: 'Pesapal' },
  { value: 'installment', label: 'Installment' },
];

const defaultForm = {
  customer_id: '',
  biller_id: '',
  warehouse_id: '',
  product_number: '16',
  keybord_active: false,
  is_table: false,
  send_sms: false,
  cash_register: false,
  show_print_invoice: false,
};

const PosSetting = () => {
  const [form, setForm] = useState(defaultForm);
  const [customers, setCustomers] = useState([]);
  const [billers, setBillers] = useState([]);
  const [warehouses, setWarehouses] = useState([]);
  const [selectedOptions, setSelectedOptions] = useState([]);
  const [customOptions, setCustomOptions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setLoading(true);
      const res = await api.get('settings/pos');
      const data = res?.data;
      if (data?.status === 200) {
        setCustomers(data.customers || []);
        setBillers(data.billers || []);
        setWarehouses(data.warehouses || []);
        const opts = data.options || [];
        const fixedValues = FIXED_PAYMENT_OPTIONS.map((o) => o.value);
        const selected = fixedValues.filter((v) => opts.includes(v));
        const custom = opts.filter((v) => v && !fixedValues.includes(v));
        setSelectedOptions(selected);
        setCustomOptions(custom.length ? custom : ['']);
        const s = data.data;
        if (s) {
          setForm({
            customer_id: s.customer_id != null ? String(s.customer_id) : '',
            biller_id: s.biller_id != null ? String(s.biller_id) : '',
            warehouse_id: s.warehouse_id != null ? String(s.warehouse_id) : '',
            product_number: s.product_number != null ? String(s.product_number) : '16',
            keybord_active: !!s.keybord_active,
            is_table: !!s.is_table,
            send_sms: !!s.send_sms,
            cash_register: !!s.cash_register,
            show_print_invoice: !!s.show_print_invoice,
          });
        }
      }
    } catch (err) {
      msg.error(err?.response?.data?.message || 'Failed to load POS setting');
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value,
    }));
  };

  const toggleOption = (value) => {
    setSelectedOptions((prev) =>
      prev.includes(value) ? prev.filter((v) => v !== value) : [...prev, value]
    );
  };

  const addCustomOption = () => {
    setCustomOptions((prev) => [...prev, '']);
  };

  const updateCustomOption = (index, val) => {
    setCustomOptions((prev) => {
      const next = [...prev];
      next[index] = val;
      return next;
    });
  };

  const removeCustomOption = (index) => {
    setCustomOptions((prev) => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.customer_id) {
      msg.error('Default Customer is required');
      return;
    }
    if (!form.biller_id) {
      msg.error('Default Biller is required');
      return;
    }
    if (!form.warehouse_id) {
      msg.error('Default Warehouse is required');
      return;
    }
    if (!form.product_number || parseInt(form.product_number, 10) < 1) {
      msg.error('Displayed Number of Product Row is required');
      return;
    }
    const customFiltered = customOptions.map((s) => s.trim()).filter(Boolean);
    const allOptions = [...selectedOptions, ...customFiltered];
    if (allOptions.length !== new Set(allOptions).size) {
      msg.error('Payment options must be unique');
      return;
    }
    setSubmitting(true);
    try {
      const payload = {
        customer_id: form.customer_id,
        biller_id: form.biller_id,
        warehouse_id: form.warehouse_id,
        product_number: parseInt(form.product_number, 10) || 16,
        keybord_active: form.keybord_active ? 1 : 0,
        is_table: form.is_table ? 1 : 0,
        send_sms: form.send_sms ? 1 : 0,
        cash_register: form.cash_register ? 1 : 0,
        show_print_invoice: form.show_print_invoice ? 1 : 0,
        options: allOptions.length ? allOptions : ['cash', 'card', 'credit'],
      };
      const res = await api.post('settings/pos').values(payload);
      const data = res?.data;
      if (res?.status === 200 && data?.status === 200) {
        msg.success(data?.message || 'POS setting saved');
        fetchData();
      } else {
        msg.error(data?.message || 'Save failed');
      }
    } catch (err) {
      const d = err?.response?.data;
      msg.error(d?.message || 'Failed to save');
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="text-center p-4">
        <p>Loading...</p>
      </div>
    );
  }

  return (
    <div>
      <h5 className="text-center">{moduleName}</h5>
      <br />
      <section className="forms">
        <div className="container-fluid">
          <div className="row">
            <div className="col-md-12">
              <div className="card">
                <div className="card-header d-flex align-items-center">
                  <h4>POS Setting</h4>
                </div>
                <div className="card-body">
                  <p className="italic">
                    <small>The field labels marked with * are required input fields.</small>
                  </p>
                  <form onSubmit={handleSubmit}>
                    <div className="row">
                      <div className="col-md-3">
                        <div className="form-group">
                          <label>Default Customer <span className="text-danger">*</span></label>
                          <select
                            name="customer_id"
                            className="form-control"
                            value={form.customer_id}
                            onChange={handleChange}
                            required
                          >
                            <option value="">Select customer...</option>
                            {customers.map((c) => (
                              <option key={c.id} value={c.id}>
                                {c.name} ({c.phone_number})
                              </option>
                            ))}
                          </select>
                        </div>
                      </div>
                      <div className="col-md-3">
                        <div className="form-group">
                          <label>Default Biller <span className="text-danger">*</span></label>
                          <select
                            name="biller_id"
                            className="form-control"
                            value={form.biller_id}
                            onChange={handleChange}
                            required
                          >
                            <option value="">Select Biller...</option>
                            {billers.map((b) => (
                              <option key={b.id} value={b.id}>
                                {b.name} ({b.company_name})
                              </option>
                            ))}
                          </select>
                        </div>
                      </div>
                      <div className="col-md-3">
                        <div className="form-group">
                          <label>Default Warehouse <span className="text-danger">*</span></label>
                          <select
                            name="warehouse_id"
                            className="form-control"
                            value={form.warehouse_id}
                            onChange={handleChange}
                            required
                          >
                            <option value="">Select warehouse...</option>
                            {warehouses.map((w) => (
                              <option key={w.id} value={w.id}>
                                {w.name}
                              </option>
                            ))}
                          </select>
                        </div>
                      </div>
                      <div className="col-md-3">
                        <div className="form-group">
                          <label>Displayed Number of Product Row <span className="text-danger">*</span></label>
                          <input
                            type="number"
                            name="product_number"
                            className="form-control"
                            value={form.product_number}
                            onChange={handleChange}
                            required
                            min={1}
                          />
                        </div>
                      </div>
                    </div>

                    <div className="row">
                      <div className="col-md-3 mt-2 mb-2">
                        <input
                          type="checkbox"
                          name="keybord_active"
                          className="mt-2"
                          checked={form.keybord_active}
                          onChange={handleChange}
                        />
                        <label className="mt-2 ml-1">Touchscreen keybord</label>
                      </div>
                      <div className="col-md-3 mt-2 mb-2">
                        <input
                          type="checkbox"
                          name="is_table"
                          className="mt-2"
                          checked={form.is_table}
                          onChange={handleChange}
                        />
                        <label className="mt-2 ml-1">Table Management</label>
                      </div>
                      <div className="col-md-3 mt-2 mb-2">
                        <input
                          type="checkbox"
                          name="send_sms"
                          className="mt-2"
                          checked={form.send_sms}
                          onChange={handleChange}
                        />
                        <label className="mt-2 ml-1" title="You'll have to set up SMS gateway settings for sending SMS (settings > SMS settings)">
                          Send SMS After Sale
                        </label>
                      </div>
                      <div className="col-md-3 mt-2 mb-2">
                        <input
                          type="checkbox"
                          name="cash_register"
                          className="mt-2"
                          checked={form.cash_register}
                          onChange={handleChange}
                        />
                        <label className="mt-2 ml-1" title="If enabled, cash register will be activated on POS page">
                          Cash Register
                        </label>
                      </div>
                      <div className="col-md-3 mt-2 mb-2">
                        <input
                          type="checkbox"
                          name="show_print_invoice"
                          className="mt-2"
                          checked={form.show_print_invoice}
                          onChange={handleChange}
                        />
                        <label className="mt-2 ml-1" title="If unchecked invoice will not print after sales">
                          Print invoice
                        </label>
                      </div>
                    </div>

                    <hr />

                    <div className="row">
                      <div className="col-md-12 mb-3">
                        <h4 title="Selected payment gateways will show on pos page">Payment Options</h4>
                      </div>
                      {FIXED_PAYMENT_OPTIONS.map((opt) => (
                        <div key={opt.value} className="form-group col-md-2">
                          <input
                            type="checkbox"
                            className="mt-2"
                            checked={selectedOptions.includes(opt.value)}
                            onChange={() => toggleOption(opt.value)}
                          />
                          <label className="mt-2 ml-1">{opt.label}</label>
                        </div>
                      ))}
                    </div>

                    <div className="row mt-3">
                      <div className="form-group col-md-12">
                        <button type="button" className="btn btn-info" onClick={addCustomOption}>
                          + Add More Payment Option
                        </button>
                      </div>
                    </div>

                    <div className="row mt-2">
                      <div className="col-md-6 form-group" id="payment-options">
                        {customOptions.map((val, index) => (
                          <div key={index} className="d-flex align-items-center mb-2">
                            <input
                              type="text"
                              className="form-control mt-2 mr-2"
                              style={{ maxWidth: 200 }}
                              placeholder="Payment Options"
                              value={val}
                              onChange={(e) => updateCustomOption(index, e.target.value)}
                            />
                            <button
                              type="button"
                              className="btn btn-danger btn-sm"
                              onClick={() => removeCustomOption(index)}
                              aria-label="Remove"
                            >
                              X
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="form-group mt-3">
                      <button type="submit" className="btn btn-primary" disabled={submitting}>
                        {submitting ? 'Saving...' : 'Submit'}
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default PosSetting;

// pos-client/src/views/pages/settings/pos-setting.vue
<script setup>
import api from '@/service/api';
import { useToast } from 'primevue/usetoast';
import { onMounted, ref } from 'vue';

const toast = useToast();
const setting = ref({});
const customers = ref([]);
const billers = ref([]);
const warehouses = ref([]);
const options = ref([]);
const customOption = ref('');
const loading = ref(false);

const paymentOptions = ['cash', 'card', 'credit', 'cheque', 'gift_card', 'deposit', 'points', 'razorpay', 'pesapal', 'installment'];

onMounted(() => fetchSetting());

async function fetchSetting() {
    try {
        const res = await api.get('settings/pos');
        if (res.data?.status === 200) {
            setting.value = res.data.data || {};
            customers.value = res.data.customers || [];
            billers.value = res.data.billers || [];
            warehouses.value = res.data.warehouses || [];
            const opts = res.data.options || ['cash', 'card', 'credit'];
            options.value = Array.isArray(opts) ? [...opts] : (opts ? opts.split(',').filter(Boolean) : ['cash', 'card']);
        }
    } catch (e) {
        toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to load POS setting', life: 3000 });
    }
}

function isSelected(val) {
    return options.value.includes(val);
}

function toggleOption(val) {
    const i = options.value.indexOf(val);
    if (i >= 0) options.value.splice(i, 1);
    else options.value.push(val);
}

function addCustomOption() {
    const v = customOption.value?.trim();
    if (v && !options.value.includes(v)) {
        options.value.push(v);
        customOption.value = '';
    }
}

function removeCustomOption(val) {
    if (paymentOptions.includes(val)) return;
    options.value = options.value.filter((o) => o !== val);
}

async function save() {
    if (!setting.value?.customer_id || !setting.value?.biller_id || !setting.value?.warehouse_id) {
        toast.add({ severity: 'error', summary: 'Validation', detail: 'Default Customer, Biller and Warehouse are required', life: 3000 });
        return;
    }
    if (!setting.value?.product_number || setting.value.product_number < 1) {
        toast.add({ severity: 'error', summary: 'Validation', detail: 'Product rows must be at least 1', life: 3000 });
        return;
    }
    loading.value = true;
    try {
        const payload = {
            customer_id: setting.value.customer_id,
            biller_id: setting.value.biller_id,
            warehouse_id: setting.value.warehouse_id,
            product_number: setting.value.product_number,
            keybord_active: !!setting.value.keybord_active,
            is_table: !!setting.value.is_table,
            send_sms: !!setting.value.send_sms,
            cash_register: !!setting.value.cash_register,
            show_print_invoice: !!setting.value.show_print_invoice,
            options: options.value
        };
        const res = await api.post('settings/pos', payload);
        if (res.data?.status === 200) {
            toast.add({ severity: 'success', summary: 'Success', detail: res.data.message, life: 3000 });
        } else {
            toast.add({ severity: 'error', summary: 'Error', detail: res.data?.message || 'Failed to save', life: 3000 });
        }
    } catch (e) {
        toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to save POS setting', life: 3000 });
    } finally {
        loading.value = false;
    }
}
</script>

<template>
    <div class="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-950 p-4 md:p-6 lg:p-8">
        <div class="mb-6">
            <h1 class="text-3xl font-bold text-gray-900 dark:text-gray-100 flex items-center gap-3">
                <i class="pi pi-desktop text-primary"></i>
                POS Setting
            </h1>
            <p class="text-gray-600 dark:text-gray-400 mt-1">Configure default options for the POS page</p>
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700 p-6">
            <p class="text-sm italic text-gray-500 dark:text-gray-400 mb-6">The field labels marked with <span class="text-red-500">*</span> are required input fields.</p>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                <div>
                    <label class="block text-sm font-semibold mb-2">Default Customer <span class="text-red-500">*</span></label>
                    <Select
                        v-model="setting.customer_id"
                        :options="customers"
                        optionLabel="name"
                        optionValue="id"
                        placeholder="Select customer"
                        class="w-full"
                    >
                        <template #option="{ option }">
                            {{ option.name }} ({{ option.phone_number || '-' }})
                        </template>
                    </Select>
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Default Biller <span class="text-red-500">*</span></label>
                    <Select
                        v-model="setting.biller_id"
                        :options="billers"
                        optionLabel="name"
                        optionValue="id"
                        placeholder="Select biller"
                        class="w-full"
                    >
                        <template #option="{ option }">
                            {{ option.name }} ({{ option.company_name || '-' }})
                        </template>
                    </Select>
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Default Warehouse <span class="text-red-500">*</span></label>
                    <Select
                        v-model="setting.warehouse_id"
                        :options="warehouses"
                        optionLabel="name"
                        optionValue="id"
                        placeholder="Select warehouse"
                        class="w-full"
                    />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Displayed Number of Product Row <span class="text-red-500">*</span></label>
                    <InputNumber v-model="setting.product_number" :min="1" :max="50" class="w-full" />
                </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                <div class="flex items-center gap-2">
                    <Checkbox v-model="setting.keybord_active" :binary="true" inputId="keybord" />
                    <label for="keybord" class="cursor-pointer">Touchscreen keyboard</label>
                </div>
                <div class="flex items-center gap-2">
                    <Checkbox v-model="setting.is_table" :binary="true" inputId="table" />
                    <label for="table" class="cursor-pointer">Table Management</label>
                </div>
                <div class="flex items-center gap-2">
                    <Checkbox v-model="setting.send_sms" :binary="true" inputId="sms" />
                    <label for="sms" class="cursor-pointer">Send SMS After Sale</label>
                </div>
                <div class="flex items-center gap-2">
                    <Checkbox v-model="setting.cash_register" :binary="true" inputId="cash" />
                    <label for="cash" class="cursor-pointer">Cash Register</label>
                </div>
                <div class="flex items-center gap-2">
                    <Checkbox v-model="setting.show_print_invoice" :binary="true" inputId="print" />
                    <label for="print" class="cursor-pointer">Print Invoice</label>
                </div>
            </div>

            <hr class="my-6 border-gray-200 dark:border-gray-600" />

            <h4 class="font-semibold mb-4">Payment Options</h4>
            <div class="flex flex-wrap gap-4 mb-4">
                <div v-for="opt in paymentOptions" :key="opt" class="flex items-center gap-2">
                    <Checkbox :modelValue="isSelected(opt)" @update:modelValue="toggleOption(opt)" :binary="true" :inputId="'opt-' + opt" />
                    <label :for="'opt-' + opt" class="cursor-pointer capitalize">{{ opt.replace('_', ' ') }}</label>
                </div>
            </div>
            <div class="flex gap-2 flex-wrap items-center">
                <span class="text-sm font-medium">Add custom:</span>
                <InputText v-model="customOption" placeholder="Payment option name" class="w-48" @keyup.enter="addCustomOption" />
                <Button label="Add" size="small" @click="addCustomOption" />
            </div>
            <div v-if="options.filter(o => !paymentOptions.includes(o)).length" class="mt-2 flex flex-wrap gap-2">
                <Tag v-for="o in options.filter(o => !paymentOptions.includes(o))" :key="o" :value="o" :removable="true" @remove="removeCustomOption(o)" />
            </div>

            <div class="mt-6">
                <Button label="Submit" icon="pi pi-check" :loading="loading" @click="save" />
            </div>
        </div>
    </div>
</template>
