// pos-client/src/views/backend/stock_count/StockCountList.jsx
import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { Link } from 'react-router-dom';
import {
    PageLayout,
    DataTable,
    TextInput,
    TextareaInput,
    Toast,
    useToast,
    Modal,
    FormField,
    FormRow,
    SelectInput,
    Pagination,
} from '../../../components/ui';
import { api } from '../../../services';
import usePermissions from '../../../stores/usePermissions';

const PAGE_SIZES = [10, 25, 50, -1];

function multiSelectValues(e) {
    return Array.from(e.target.selectedOptions).map((o) => o.value);
}

export default function StockCountList({ controllerName }) {
    const [rows, setRows] = useState([]);
    const [warehouses, setWarehouses] = useState([]);
    const [categories, setCategories] = useState([]);
    const [brands, setBrands] = useState([]);
    const [decimal, setDecimal] = useState(2);
    const [loading, setLoading] = useState(true);
    const [pageSize, setPageSize] = useState(10);
    const [page, setPage] = useState(1);
    const [search, setSearch] = useState('');
    const { toast, showToast } = useToast();

    const [createOpen, setCreateOpen] = useState(false);
    const [finalizeOpen, setFinalizeOpen] = useState(null);
    const [reportOpen, setReportOpen] = useState(null);
    const [reportDiff, setReportDiff] = useState(null);
    const [reportLoading, setReportLoading] = useState(false);
    const [submitting, setSubmitting] = useState(false);

    const [createForm, setCreateForm] = useState({
        warehouse_id: '',
        category_ids: [],
        brand_ids: [],
    });
    const [finalizeForm, setFinalizeForm] = useState({ file: null, note: '' });

    const perms = usePermissions(controllerName || 'stock_count');
    const canAdd = perms.canAdd || perms.canView;

    const fetchList = useCallback(async () => {
        setLoading(true);
        try {
            const res = await api.get('stock-count');
            setRows(res.data?.data || []);
            setWarehouses(res.data?.warehouses || []);
            setCategories(res.data?.categories || []);
            setBrands(res.data?.brands || []);
            setDecimal(res.data?.decimal ?? 2);
        } catch (err) {
            showToast(err?.message || 'Failed to load stock counts.', 'error');
        } finally {
            setLoading(false);
        }
    }, [showToast]);

    useEffect(() => {
        fetchList();
    }, [fetchList]);

    const filtered = useMemo(() => {
        if (!search.trim()) return rows;
        const q = search.toLowerCase();
        return rows.filter((r) =>
            (r.reference_no || '').toLowerCase().includes(q) ||
            (r.warehouse_name || '').toLowerCase().includes(q) ||
            (r.category_label || '').toLowerCase().includes(q) ||
            (r.brand_label || '').toLowerCase().includes(q)
        );
    }, [rows, search]);

    const paginated = useMemo(() => {
        if (pageSize === -1) return filtered;
        const start = (page - 1) * pageSize;
        return filtered.slice(start, start + pageSize);
    }, [filtered, page, pageSize]);

    const totalPages = pageSize === -1 ? 1 : Math.max(1, Math.ceil(filtered.length / pageSize) || 1);

    const handleCreate = async (e) => {
        e.preventDefault();
        if (!createForm.warehouse_id) {
            showToast('Warehouse is required.', 'error');
            return;
        }
        setSubmitting(true);
        try {
            const fd = new FormData();
            fd.append('warehouse_id', createForm.warehouse_id);
            createForm.category_ids.forEach((id) => fd.append('category_id[]', id));
            createForm.brand_ids.forEach((id) => fd.append('brand_id[]', id));
            const res = await api.post('stock-count', fd);
            showToast(res.data?.message || 'Stock count created.', 'success');
            setCreateOpen(false);
            setCreateForm({ warehouse_id: '', category_ids: [], brand_ids: [] });
            fetchList();
            if (res.data?.initial_file_url) {
                window.open(res.data.initial_file_url, '_blank');
            }
        } catch (err) {
            showToast(err?.message || 'Failed to create stock count.', 'error');
        } finally {
            setSubmitting(false);
        }
    };

    const handleFinalize = async (e) => {
        e.preventDefault();
        if (!finalizeForm.file) {
            showToast('Please upload a CSV file.', 'error');
            return;
        }
        setSubmitting(true);
        try {
            const fd = new FormData();
            fd.append('stock_count_id', String(finalizeOpen.id));
            fd.append('final_file', finalizeForm.file);
            fd.append('note', finalizeForm.note || '');
            await api.post('stock-count/finalize', fd);
            showToast('Stock count finalized successfully.', 'success');
            setFinalizeOpen(null);
            setFinalizeForm({ file: null, note: '' });
            fetchList();
        } catch (err) {
            showToast(err?.message || 'Failed to finalize stock count.', 'error');
        } finally {
            setSubmitting(false);
        }
    };

    const openReport = async (row) => {
        setReportOpen(row);
        setReportDiff(null);
        setReportLoading(true);
        try {
            const res = await api.get(`stock-count/stockdif/${row.id}`);
            setReportDiff(res.data || {});
        } catch (err) {
            showToast(err?.message || 'Failed to load report.', 'error');
            setReportOpen(null);
        } finally {
            setReportLoading(false);
        }
    };

    const columns = [
        { label: 'Date', key: 'date' },
        { label: 'Reference', key: 'reference_no' },
        { label: 'Warehouse', key: 'warehouse_name' },
        { label: 'Category', key: 'category_label' },
        { label: 'Brand', key: 'brand_label' },
        {
            label: 'Type',
            key: 'type_label',
            render: (row) => (
                <span className={`badge ${row.type === 'full' ? 'bg-primary' : 'bg-info'}`}>
                    {row.type_label}
                </span>
            ),
        },
        {
            label: 'Initial',
            key: 'initial_file',
            render: (row) =>
                row.initial_file_url ? (
                    <a href={row.initial_file_url} download title="Download initial file">⬇</a>
                ) : null,
        },
        {
            label: 'Final',
            key: 'final_file',
            render: (row) =>
                row.final_file_url ? (
                    <a href={row.final_file_url} download title="Download final file">⬇</a>
                ) : null,
        },
        {
            label: 'Action',
            key: 'action',
            render: (row) =>
                row.has_final_file ? (
                    <button
                        type="button"
                        className="ui-btn btn-sm"
                        style={{ background: '#28a745', color: '#fff' }}
                        onClick={() => openReport(row)}
                    >
                        Final Report
                    </button>
                ) : (
                    <button
                        type="button"
                        className="ui-btn primary btn-sm"
                        onClick={() => {
                            setFinalizeOpen(row);
                            setFinalizeForm({ file: null, note: '' });
                        }}
                    >
                        Finalize
                    </button>
                ),
        },
    ];

    return (
        <PageLayout eyebrow="Product" title="Stock Count">
            <div className="d-flex flex-wrap gap-2 mb-3 align-items-center">
                {canAdd && (
                    <button type="button" className="ui-btn primary" onClick={() => setCreateOpen(true)}>
                        Count Stock
                    </button>
                )}
                <div style={{ marginLeft: 'auto', width: 260 }}>
                    <TextInput
                        placeholder="Search reference, warehouse..."
                        value={search}
                        onChange={(e) => { setSearch(e.target.value); setPage(1); }}
                    />
                </div>
            </div>

            <DataTable
                columns={columns}
                rows={paginated}
                loading={loading}
                emptyText="No stock counts found."
            />

            <Pagination
                page={page}
                totalPages={totalPages}
                pageSize={pageSize === -1 ? filtered.length || 10 : pageSize}
                totalRows={filtered.length}
                onChange={setPage}
                pageSizes={PAGE_SIZES}
                onPageSize={(s) => { setPageSize(s); setPage(1); }}
            />

            {createOpen && (
                <Modal title="Count Stock" onClose={() => setCreateOpen(false)}>
                    <form onSubmit={handleCreate}>
                        <p className="text-muted small">
                            Fields marked * are required. Leave category and brand empty for a full warehouse count.
                        </p>
                        <FormRow>
                            <FormField label="Warehouse" required>
                                <SelectInput
                                    required
                                    value={createForm.warehouse_id}
                                    onChange={(e) => setCreateForm({ ...createForm, warehouse_id: e.target.value })}
                                    options={[
                                        { value: '', label: 'Select warehouse...' },
                                        ...warehouses.map((w) => ({ value: String(w.id), label: w.name })),
                                    ]}
                                />
                            </FormField>
                            <FormField label="Category">
                                <select
                                    className="ui-select-field"
                                    multiple
                                    size={5}
                                    value={createForm.category_ids}
                                    onChange={(e) => setCreateForm({
                                        ...createForm,
                                        category_ids: multiSelectValues(e),
                                    })}
                                >
                                    {categories.map((c) => (
                                        <option key={c.id} value={String(c.id)}>{c.name}</option>
                                    ))}
                                </select>
                            </FormField>
                            <FormField label="Brand">
                                <select
                                    className="ui-select-field"
                                    multiple
                                    size={5}
                                    value={createForm.brand_ids}
                                    onChange={(e) => setCreateForm({
                                        ...createForm,
                                        brand_ids: multiSelectValues(e),
                                    })}
                                >
                                    {brands.map((b) => (
                                        <option key={b.id} value={String(b.id)}>{b.title}</option>
                                    ))}
                                </select>
                            </FormField>
                        </FormRow>
                        <div className="d-flex gap-2 mt-3">
                            <button type="submit" className="ui-btn primary" disabled={submitting}>
                                {submitting ? 'Saving...' : 'Submit'}
                            </button>
                            <button type="button" className="ui-btn" onClick={() => setCreateOpen(false)}>Cancel</button>
                        </div>
                    </form>
                </Modal>
            )}

            {finalizeOpen && (
                <Modal title="Finalize Stock Count" onClose={() => setFinalizeOpen(null)}>
                    <form onSubmit={handleFinalize}>
                        <p className="text-muted small">
                            Upload the initial CSV after filling the Counted column.
                        </p>
                        <FormField label="Upload CSV file" required>
                            <input
                                type="file"
                                accept=".csv"
                                className="ui-input"
                                required
                                onChange={(e) => setFinalizeForm({ ...finalizeForm, file: e.target.files?.[0] || null })}
                            />
                        </FormField>
                        <FormField label="Note">
                            <TextareaInput
                                rows={3}
                                value={finalizeForm.note}
                                onChange={(e) => setFinalizeForm({ ...finalizeForm, note: e.target.value })}
                            />
                        </FormField>
                        <div className="d-flex gap-2 mt-3">
                            <button type="submit" className="ui-btn primary" disabled={submitting}>
                                {submitting ? 'Saving...' : 'Submit'}
                            </button>
                            <button type="button" className="ui-btn" onClick={() => setFinalizeOpen(null)}>Cancel</button>
                        </div>
                    </form>
                </Modal>
            )}

            {reportOpen && (
                <Modal title="Stock Count Report" onClose={() => setReportOpen(null)}>
                    <div className="mb-3 small">
                        <div><strong>Date:</strong> {reportOpen.date}</div>
                        <div><strong>Reference:</strong> {reportOpen.reference_no}</div>
                        <div><strong>Warehouse:</strong> {reportOpen.warehouse_name}</div>
                        <div><strong>Type:</strong> {reportOpen.type_label}</div>
                        {reportOpen.category_label && <div><strong>Category:</strong> {reportOpen.category_label}</div>}
                        {reportOpen.brand_label && <div><strong>Brand:</strong> {reportOpen.brand_label}</div>}
                        <div className="mt-2 d-flex gap-2">
                            {reportOpen.initial_file_url && (
                                <a href={reportOpen.initial_file_url} className="ui-btn btn-sm" download>Initial file</a>
                            )}
                            {reportOpen.final_file_url && (
                                <a href={reportOpen.final_file_url} className="ui-btn btn-sm" download>Final file</a>
                            )}
                        </div>
                    </div>

                    {reportLoading && <p>Loading differences…</p>}

                    {!reportLoading && reportDiff?.products?.length > 0 && (
                        <>
                            <div className="table-responsive">
                                <table className="table table-bordered table-sm">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Product</th>
                                            <th>Expected</th>
                                            <th>Counted</th>
                                            <th>Difference</th>
                                            <th>Cost</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {reportDiff.products.map((name, i) => (
                                            <tr key={i}>
                                                <td>{i + 1}</td>
                                                <td>{name}</td>
                                                <td>{Number(reportDiff.expected[i]).toFixed(decimal)}</td>
                                                <td>{Number(reportDiff.counted[i]).toFixed(decimal)}</td>
                                                <td>{Number(reportDiff.difference[i]).toFixed(decimal)}</td>
                                                <td>{Number(reportDiff.cost[i]).toFixed(decimal)}</td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                            {!reportDiff.is_adjusted && (
                                <Link
                                    to={`/stock-count/${reportOpen.id}/qty_adjustment`}
                                    className="ui-btn primary"
                                    onClick={() => setReportOpen(null)}
                                >
                                    Add Adjustment
                                </Link>
                            )}
                        </>
                    )}

                    {!reportLoading && (!reportDiff?.products || reportDiff.products.length === 0) && (
                        <p className="text-muted">No differences found — stock matches counted quantities.</p>
                    )}
                </Modal>
            )}

            <Toast toast={toast} />
        </PageLayout>
    );
}

// pos-client/src/views/pages/stock-count/stock-count-list.vue
<script setup>
import api from '@/service/api';
import { useToast } from 'primevue/usetoast';
import { format } from 'date-fns';
import { onMounted, reactive, ref, watch } from 'vue';
import { useRouter } from 'vue-router';

const toast = useToast();
const router = useRouter();

const loading = ref(false);
const stockCounts = ref([]);

const meta = reactive({
    page: 1,
    perPage: 15,
    total: 0,
    lastPage: 1
});

const filters = reactive({
    warehouseId: 'all',
    search: ''
});

const selection = ref([]);

const warehouses = ref([]);
const categories = ref([]);
const brands = ref([]);

const createDialogVisible = ref(false);
const finalizeDialogVisible = ref(false);
const reportDialogVisible = ref(false);

const createForm = reactive({
    warehouse_id: null,
    category_ids: [],
    brand_ids: []
});

const finalizeForm = reactive({
    stock_count_id: null,
    note: '',
    final_file: null
});

const reportData = reactive({
    headers: null,
    rows: [],
    is_adjusted: false
});

const reportLoading = ref(false);
let searchDebounceHandle = null;

onMounted(async () => {
    await fetchOptions();
    await fetchStockCounts();
});

watch(
    () => filters.warehouseId,
    async () => {
        await fetchStockCounts(1);
    }
);

watch(
    () => filters.search,
    (value) => {
        if (searchDebounceHandle) clearTimeout(searchDebounceHandle);
        searchDebounceHandle = setTimeout(() => {
            fetchStockCounts(1);
        }, 400);
    }
);

async function fetchOptions() {
    try {
        const response = await api.get('stock-counts/options');
        if (response.data) {
            warehouses.value = [
                { label: 'All Warehouses', value: 'all' },
                ...(response.data.warehouses || []).map((warehouse) => ({
                    label: warehouse.name,
                    value: String(warehouse.id)
                }))
            ];
            categories.value = (response.data.categories || []).map((category) => ({
                label: category.name,
                value: category.id
            }));
            brands.value = (response.data.brands || []).map((brand) => ({
                label: brand.title,
                value: brand.id
            }));
        }
    } catch (error) {
        console.error('Failed to fetch stock count options', error);
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: 'Unable to load stock count options.',
            life: 3000
        });
    }
}

async function fetchStockCounts(page = 1) {
    loading.value = true;
    try {
        const params = new URLSearchParams();
        params.set('page', String(page));
        params.set('per_page', String(meta.perPage));

        if (filters.search) params.set('search', filters.search);
        if (filters.warehouseId !== 'all') params.set('warehouse_id', filters.warehouseId);
        const response = await api.get(`stock-counts?${params.toString()}`);
        if (response.data) {
            stockCounts.value = response.data.data || [];
            meta.page = response.data.meta?.current_page || page;
            meta.perPage = response.data.meta?.per_page || meta.perPage;
            meta.total = response.data.meta?.total || 0;
            meta.lastPage = response.data.meta?.last_page || 1;
        }
    } catch (error) {
        console.error('Failed to load stock counts', error);
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: 'Unable to load stock counts.',
            life: 3000
        });
    } finally {
        loading.value = false;
    }
}

function onPage(event) {
    meta.perPage = event.rows;
    fetchStockCounts(event.page + 1);
}

function openCreateDialog() {
    createForm.warehouse_id = null;
    createForm.category_ids = [];
    createForm.brand_ids = [];
    createDialogVisible.value = true;
}

async function submitCreate() {
    if (!createForm.warehouse_id) {
        toast.add({
            severity: 'warn',
            summary: 'Validation',
            detail: 'Please select a warehouse.',
            life: 2500
        });
        return;
    }

    try {
        const payload = {
            warehouse_id: createForm.warehouse_id,
            category_ids: createForm.category_ids,
            brand_ids: createForm.brand_ids
        };
        const response = await api.post('stock-counts', payload);
        toast.add({
            severity: 'success',
            summary: 'Created',
            detail: response.data?.message || 'Stock count created successfully.',
            life: 3000
        });
        createDialogVisible.value = false;
        await fetchStockCounts(meta.page);
        if (response.data?.initial_file_url) {
            window.open(response.data.initial_file_url, '_blank');
        }
    } catch (error) {
        console.error('Failed to create stock count', error);
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.response?.data?.message || 'Unable to create stock count.',
            life: 3000
        });
    }
}

function openFinalizeDialog(stockCount) {
    finalizeForm.stock_count_id = stockCount.id;
    finalizeForm.note = '';
    finalizeForm.final_file = null;
    finalizeDialogVisible.value = true;
}

function handleFinalizeFileChange(event) {
    const [file] = event.target.files || [];
    finalizeForm.final_file = file || null;
}

async function submitFinalize() {
    if (!finalizeForm.final_file) {
        toast.add({
            severity: 'warn',
            summary: 'Validation',
            detail: 'Please select a CSV file to upload.',
            life: 2500
        });
        return;
    }

    try {
        const formData = new FormData();
        formData.append('final_file', finalizeForm.final_file);
        if (finalizeForm.note) {
            formData.append('note', finalizeForm.note);
        }

        await api.post(`stock-counts/${finalizeForm.stock_count_id}/finalize`, formData);
        toast.add({
            severity: 'success',
            summary: 'Finalized',
            detail: 'Stock count finalized successfully.',
            life: 3000
        });
        finalizeDialogVisible.value = false;
        await fetchStockCounts(meta.page);
    } catch (error) {
        console.error('Failed to finalize stock count', error);
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.response?.data?.message || 'Unable to finalize stock count.',
            life: 3000
        });
    }
}

async function openReport(stockCount) {
    reportDialogVisible.value = true;
    reportLoading.value = true;
    reportData.headers = null;
    reportData.rows = [];
    reportData.is_adjusted = false;

    try {
        const response = await api.get(`stock-counts/${stockCount.id}/difference`);
        if (response.data?.data) {
            reportData.headers = response.data.data.headers;
            reportData.rows = response.data.data.rows || [];
            reportData.is_adjusted = !!response.data.data.is_adjusted;
        }
    } catch (error) {
        console.error('Failed to load stock count difference', error);
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.response?.data?.message || 'Unable to load stock count report.',
            life: 3000
        });
        reportDialogVisible.value = false;
    } finally {
        reportLoading.value = false;
    }
}

function downloadFile(url) {
    if (!url) return;
    window.open(url, '_blank');
}

function categoriesLabel(stockCount) {
    const names = stockCount.categories || [];
    return names.length ? names.join(', ') : '—';
}

function brandsLabel(stockCount) {
    const names = stockCount.brands || [];
    return names.length ? names.join(', ') : '—';
}

function typeSeverity(type) {
    return type === 'full' ? 'primary' : 'info';
}

function formatDate(value) {
    if (!value) return '';
    return format(new Date(value), 'yyyy-MM-dd HH:mm');
}

async function deleteStockCount(stockCount) {
    const confirmed = window.confirm('Are you sure you want to delete this stock count?');
    if (!confirmed) return;

    try {
        await api.delete(`stock-counts/${stockCount.id}`);
        toast.add({
            severity: 'success',
            summary: 'Deleted',
            detail: 'Stock count deleted successfully.',
            life: 2500
        });
        await fetchStockCounts(meta.page);
    } catch (error) {
        console.error('Failed to delete stock count', error);
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: 'Unable to delete stock count.',
            life: 3000
        });
    }
}

function navigateToAdjustment() {
    if (!reportData.headers?.stock_count_id) return;
    router.push({
        path: '/inventory/adjustments/create',
        query: { stockCountId: reportData.headers.stock_count_id }
    });
    reportDialogVisible.value = false;
}
</script>

<template>
    <div class="min-h-screen bg-surface-50 dark:bg-surface-900 p-4 md:p-6 lg:p-8">
        <div class="card shadow-sm mb-4">
            <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-3 mb-4">
                <div>
                    <h2 class="text-2xl font-semibold text-surface-900 dark:text-surface-0 flex items-center gap-3">
                        <i class="pi pi-clipboard text-primary-500 text-2xl"></i>
                        Stock Counts
                    </h2>
                    <p class="text-surface-500 dark:text-surface-400">
                        Manage stock count sessions, download templates, and review differences.
                    </p>
                </div>
                <div class="flex flex-wrap gap-2">
                    <Button label="Count Stock" icon="pi pi-plus" @click="openCreateDialog" />
                </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                <div>
                    <label class="filter-label">Warehouse</label>
                    <Dropdown
                        v-model="filters.warehouseId"
                        :options="warehouses"
                        optionLabel="label"
                        optionValue="value"
                        class="w-full"
                    />
                </div>
                <div class="md:col-span-2">
                    <label class="filter-label">Search</label>
                    <span class="p-input-icon-left w-full">
                        <i class="pi pi-search" />
                        <InputText v-model="filters.search" class="w-full" placeholder="Search reference or note" />
                    </span>
                </div>
            </div>

            <DataTable
                :value="stockCounts"
                :loading="loading"
                dataKey="id"
                paginator
                lazy
                :rows="meta.perPage"
                :totalRecords="meta.total"
                :rowsPerPageOptions="[10, 15, 25, 50]"
                responsiveLayout="scroll"
                @page="onPage"
                v-model:selection="selection"
                selectionMode="multiple"
            >
                <Column selectionMode="multiple" headerStyle="width: 3rem" />
                <Column header="Date">
                    <template #body="{ data }">
                        {{ formatDate(data.created_at) }}
                    </template>
                </Column>
                <Column field="reference_no" header="Reference" />
                <Column header="Warehouse">
                    <template #body="{ data }">
                        {{ data.warehouse?.name || '—' }}
                    </template>
                </Column>
                <Column header="Categories">
                    <template #body="{ data }">
                        {{ categoriesLabel(data) }}
                    </template>
                </Column>
                <Column header="Brands">
                    <template #body="{ data }">
                        {{ brandsLabel(data) }}
                    </template>
                </Column>
                <Column header="Type">
                    <template #body="{ data }">
                        <Tag :value="data.type === 'full' ? 'Full' : 'Partial'" :severity="typeSeverity(data.type)" />
                    </template>
                </Column>
                <Column header="Initial File" style="width: 120px">
                    <template #body="{ data }">
                        <Button
                            v-if="data.initial_file_url"
                            icon="pi pi-download"
                            text
                            size="small"
                            @click="downloadFile(data.initial_file_url)"
                        />
                        <span v-else>—</span>
                    </template>
                </Column>
                <Column header="Final File" style="width: 120px">
                    <template #body="{ data }">
                        <Button
                            v-if="data.final_file_url"
                            icon="pi pi-download"
                            text
                            size="small"
                            severity="info"
                            @click="downloadFile(data.final_file_url)"
                        />
                        <span v-else>—</span>
                    </template>
                </Column>
                <Column header="Actions" style="width: 220px">
                    <template #body="{ data }">
                        <div class="flex gap-2">
                            <Button
                                v-if="data.final_file_url"
                                icon="pi pi-chart-bar"
                                label="Final Report"
                                size="small"
                                outlined
                                @click="openReport(data)"
                            />
                            <Button
                                v-else
                                icon="pi pi-upload"
                                label="Finalize"
                                size="small"
                                severity="success"
                                outlined
                                @click="openFinalizeDialog(data)"
                            />
                            <Button icon="pi pi-trash" size="small" severity="danger" outlined @click="deleteStockCount(data)" />
                        </div>
                    </template>
                </Column>
                <template #empty>
                    <div class="py-6 text-center text-surface-500">
                        No stock count sessions found. Start a new count to populate this list.
                    </div>
                </template>
            </DataTable>
        </div>

        <!-- Create Dialog -->
        <Dialog v-model:visible="createDialogVisible" header="Count Stock" :style="{ width: '35rem' }" modal>
            <div class="grid grid-cols-1 gap-4">
                <div>
                    <label class="field-label">Warehouse *</label>
                    <Dropdown
                        v-model="createForm.warehouse_id"
                        :options="warehouses.filter((option) => option.value !== 'all')"
                        optionLabel="label"
                        optionValue="value"
                        placeholder="Select warehouse"
                        class="w-full"
                    />
                </div>
                <div>
                    <label class="field-label">Categories</label>
                    <MultiSelect
                        v-model="createForm.category_ids"
                        :options="categories"
                        optionLabel="label"
                        optionValue="value"
                        placeholder="Select categories"
                        display="chip"
                        class="w-full"
                    />
                </div>
                <div>
                    <label class="field-label">Brands</label>
                    <MultiSelect
                        v-model="createForm.brand_ids"
                        :options="brands"
                        optionLabel="label"
                        optionValue="value"
                        placeholder="Select brands"
                        display="chip"
                        class="w-full"
                    />
                </div>
            </div>
            <template #footer>
                <Button label="Cancel" icon="pi pi-times" text @click="createDialogVisible = false" />
                <Button label="Create" icon="pi pi-check" @click="submitCreate" />
            </template>
        </Dialog>

        <!-- Finalize Dialog -->
        <Dialog v-model:visible="finalizeDialogVisible" header="Finalize Stock Count" :style="{ width: '32rem' }" modal>
            <div class="space-y-4">
                <div>
                    <label class="field-label">Upload File (CSV) *</label>
                    <input
                        type="file"
                        accept=".csv"
                        class="p-inputtext w-full"
                        @change="handleFinalizeFileChange"
                    />
                </div>
                <div>
                    <label class="field-label">Note</label>
                    <Textarea v-model="finalizeForm.note" rows="3" autoResize class="w-full" />
                </div>
            </div>
            <template #footer>
                <Button label="Cancel" icon="pi pi-times" text @click="finalizeDialogVisible = false" />
                <Button label="Finalize" icon="pi pi-upload" @click="submitFinalize" />
            </template>
        </Dialog>

        <!-- Report Dialog -->
        <Dialog v-model:visible="reportDialogVisible" header="Stock Count Report" :style="{ width: '70vw' }" modal>
            <div v-if="reportLoading" class="py-10 text-center">
                <ProgressSpinner />
            </div>
            <div v-else-if="reportData.headers">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-3 mb-4 text-sm text-surface-700 dark:text-surface-200">
                    <div><strong>Date:</strong> {{ formatDate(reportData.headers.date) }}</div>
                    <div><strong>Reference:</strong> {{ reportData.headers.reference_no }}</div>
                    <div><strong>Warehouse:</strong> {{ reportData.headers.warehouse_name }}</div>
                    <div><strong>Type:</strong> {{ reportData.headers.type === 'full' ? 'Full' : 'Partial' }}</div>
                    <div v-if="reportData.headers.categories?.length">
                        <strong>Categories:</strong> {{ reportData.headers.categories.join(', ') }}
                    </div>
                    <div v-if="reportData.headers.brands?.length">
                        <strong>Brands:</strong> {{ reportData.headers.brands.join(', ') }}
                    </div>
                    <div class="flex gap-2 flex-wrap">
                        <Button
                            v-if="reportData.headers.initial_file_url"
                            label="Initial File"
                            size="small"
                            icon="pi pi-download"
                            outlined
                            @click="downloadFile(reportData.headers.initial_file_url)"
                        />
                        <Button
                            v-if="reportData.headers.final_file_url"
                            label="Final File"
                            size="small"
                            icon="pi pi-download"
                            outlined
                            severity="info"
                            @click="downloadFile(reportData.headers.final_file_url)"
                        />
                    </div>
                </div>

                <DataTable :value="reportData.rows" responsiveLayout="scroll">
                    <Column header="#" style="width: 60px">
                        <template #body="{ index }">{{ index + 1 }}</template>
                    </Column>
                    <Column field="name" header="Product" />
                    <Column field="expected" header="Expected">
                        <template #body="{ data }">{{ Number(data.expected || 0).toFixed(2) }}</template>
                    </Column>
                    <Column field="counted" header="Counted">
                        <template #body="{ data }">{{ Number(data.counted || 0).toFixed(2) }}</template>
                    </Column>
                    <Column field="difference" header="Difference">
                        <template #body="{ data }">{{ Number(data.difference || 0).toFixed(2) }}</template>
                    </Column>
                    <Column field="cost" header="Cost Impact">
                        <template #body="{ data }">{{ Number(data.cost || 0).toFixed(2) }}</template>
                    </Column>
                </DataTable>

                <div class="flex justify-end gap-2 mt-4">
                    <Button
                        v-if="!reportData.is_adjusted && reportData.rows.some((row) => Math.abs(Number(row.difference || 0)) > 0)"
                        label="Add Adjustment"
                        icon="pi pi-plus"
                        severity="warning"
                        @click="navigateToAdjustment"
                    />
                    <Button label="Close" icon="pi pi-times" text @click="reportDialogVisible = false" />
                </div>
            </div>
            <div v-else class="py-6 text-center text-surface-500">
                Report data unavailable.
            </div>
        </Dialog>
    </div>
</template>

<style scoped>
.card {
    background: var(--surface-card);
    border-radius: 1.25rem;
    border: 1px solid var(--surface-border);
    padding: 1.5rem;
}

.filter-label,
.field-label {
    display: block;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 0.45rem;
    color: var(--surface-500);
}
</style>
