// pos-client-v/src/views/pages/settings/discount-plan.vue
<script setup>
import api from '@/service/api';
import { useToast } from 'primevue/usetoast';
import { onMounted, ref, watch } from 'vue';

const toast = useToast();
const plans = ref([]);
const customers = ref([]);
const planDialog = ref(false);
const plan = ref({ name: '', type: 'limited', customer_id: [], is_active: true });
const submitted = ref(false);
const loading = ref(false);
const isEdit = ref(false);

onMounted(() => {
    fetchPlans();
    fetchFormData();
});

async function fetchPlans() {
    try {
        const res = await api.get('discount-plans');
        if (res.data?.status === 200) {
            plans.value = res.data.data || [];
        } else if (res.error) {
            toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to load discount plans', life: 3000 });
        }
    } catch (e) {
        toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to load discount plans', life: 3000 });
    }
}

async function fetchFormData() {
    try {
        const res = await api.get('discount-plans/form-data');
        if (res.data?.status === 200 && res.data.data?.customers) {
            customers.value = res.data.data.customers;
        }
    } catch (e) {
        toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to load form data', life: 3000 });
    }
}

const customerOptions = () =>
    customers.value.map((c) => ({ label: `${c.name} (${c.phone_number || ''})`, value: c.id }));

function openNew() {
    plan.value = { name: '', type: 'limited', customer_id: [], is_active: true };
    submitted.value = false;
    isEdit.value = false;
    planDialog.value = true;
}

function editPlan(p) {
    plan.value = {
        id: p.id,
        name: p.name,
        type: p.type || 'limited',
        customer_id: (p.customers || []).map((c) => c.id),
        is_active: p.is_active !== false,
    };
    isEdit.value = true;
    planDialog.value = true;
}

watch(
    () => plan.value.type,
    (val) => {
        if (val === 'generic') {
            plan.value.customer_id = customers.value.map((c) => c.id);
        } else if (isEdit.value && plan.value.id) {
            // keep current selection for limited
        } else {
            plan.value.customer_id = [];
        }
    }
);

function hideDialog() {
    planDialog.value = false;
    plan.value = {};
}

async function save() {
    submitted.value = true;
    if (!plan.value?.name?.trim()) {
        toast.add({ severity: 'error', summary: 'Validation', detail: 'Name is required', life: 3000 });
        return;
    }
    if (!plan.value.customer_id?.length) {
        toast.add({ severity: 'error', summary: 'Validation', detail: 'Select at least one customer', life: 3000 });
        return;
    }
    loading.value = true;
    try {
        const payload = {
            name: plan.value.name.trim(),
            type: plan.value.type,
            customer_id: plan.value.customer_id,
            is_active: plan.value.is_active,
        };
        if (isEdit.value && plan.value.id) {
            const res = await api.post(`discount-plans/${plan.value.id}`, payload);
            if (res.data?.status === 200) {
                toast.add({ severity: 'success', summary: 'Success', detail: res.data.message, life: 3000 });
                await fetchPlans();
                hideDialog();
            } else {
                toast.add({ severity: 'error', summary: 'Error', detail: res.data?.message || 'Failed to update', life: 3000 });
            }
        } else {
            const res = await api.post('discount-plans', payload);
            if (res.data?.status === 200) {
                toast.add({ severity: 'success', summary: 'Success', detail: res.data.message, life: 3000 });
                await fetchPlans();
                hideDialog();
            } else {
                toast.add({ severity: 'error', summary: 'Error', detail: res.data?.message || 'Failed to create', life: 3000 });
            }
        }
    } catch (e) {
        const msg = e.response?.data?.message || 'Failed to save discount plan';
        toast.add({ severity: 'error', summary: 'Error', detail: typeof msg === 'object' ? JSON.stringify(msg) : msg, life: 3000 });
    } finally {
        loading.value = false;
    }
}

function customerNames(planItem) {
    const custs = planItem.customers || [];
    return custs.length ? custs.map((c) => c.name).join(', ') : '—';
}
</script>

<template>
    <div class="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-950 p-4 md:p-6 lg:p-8">
        <div class="mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
                <h1 class="text-3xl font-bold text-gray-900 dark:text-gray-100 flex items-center gap-3">
                    <i class="pi pi-percentage text-primary"></i>
                    Discount Plan
                </h1>
                <p class="text-gray-600 dark:text-gray-400 mt-1">Manage discount plans and assigned customers</p>
            </div>
            <Button label="Create Discount Plan" icon="pi pi-plus" @click="openNew" />
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700 overflow-hidden">
            <DataTable :value="plans" stripedRows class="p-datatable-sm">
                <template #empty>
                    <div class="text-center py-12 text-gray-500">No discount plans found</div>
                </template>
                <Column field="id" header="#" style="width: 60px">
                    <template #body="slot">{{ slot.index + 1 }}</template>
                </Column>
                <Column field="name" header="Name" sortable />
                <Column header="Customer">
                    <template #body="slot">{{ customerNames(slot.data) }}</template>
                </Column>
                <Column field="type" header="Type">
                    <template #body="slot">{{ (slot.data.type || 'limited').charAt(0).toUpperCase() + (slot.data.type || 'limited').slice(1) }}</template>
                </Column>
                <Column header="Status">
                    <template #body="slot">
                        <Tag :value="slot.data.is_active ? 'Active' : 'Inactive'" :severity="slot.data.is_active ? 'success' : 'secondary'" />
                    </template>
                </Column>
                <Column header="Action" style="width: 120px">
                    <template #body="slot">
                        <Button icon="pi pi-pencil" size="small" outlined severity="info" v-tooltip="'Edit'" @click="editPlan(slot.data)" />
                    </template>
                </Column>
            </DataTable>
        </div>

        <Dialog v-model:visible="planDialog" :style="{ width: '500px' }" :header="isEdit ? 'Update Discount Plan' : 'Create Discount Plan'" :modal="true" :dismissableMask="true">
            <p class="text-sm italic text-gray-500 mb-4">The field labels marked with <span class="text-red-500">*</span> are required input fields.</p>
            <div class="space-y-4">
                <div>
                    <label class="block text-sm font-semibold mb-2">Name <span class="text-red-500">*</span></label>
                    <InputText v-model="plan.name" placeholder="Plan name" class="w-full" :invalid="submitted && !plan.name" />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Customer <span class="text-red-500">*</span></label>
                    <MultiSelect
                        v-model="plan.customer_id"
                        :options="customerOptions()"
                        optionLabel="label"
                        optionValue="value"
                        placeholder="Select customers..."
                        filter
                        class="w-full"
                        :invalid="submitted && !plan.customer_id?.length"
                        :disabled="plan.type === 'generic'"
                    />
                    <small v-if="plan.type === 'generic'" class="text-gray-500">Generic type includes all customers</small>
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Type <span class="text-red-500">*</span></label>
                    <Select v-model="plan.type" :options="[{ label: 'Limited', value: 'limited' }, { label: 'Generic', value: 'generic' }]" optionLabel="label" optionValue="value" class="w-full" />
                </div>
                <div class="flex items-center gap-2">
                    <Checkbox v-model="plan.is_active" :binary="true" inputId="plan-active" />
                    <label for="plan-active" class="cursor-pointer">Active</label>
                </div>
            </div>
            <template #footer>
                <Button label="Cancel" icon="pi pi-times" outlined @click="hideDialog" />
                <Button :label="isEdit ? 'Update' : 'Submit'" icon="pi pi-check" :loading="loading" @click="save" />
            </template>
        </Dialog>
    </div>
</template>

// pos-client/src/views/master/DiscountPlan.jsx
import React, { useState, useEffect } from 'react';
import { faTimes, faPlus, faCheck } from '@fortawesome/free-solid-svg-icons';
import Select from 'react-select';
import { api, msg } from '../../services';
import { FormModal, ListView, SystemButton, SafeFontAwesomeIcon } from '../../components';

const moduleName = 'Discount Plan';

const TYPE_OPTIONS = [
  { value: 'limited', label: 'Limited' },
  { value: 'generic', label: 'Generic' },
];

const defaultForm = {
  name: '',
  type: 'limited',
  customer_id: [],
  is_active: true,
};

const DiscountPlan = () => {
  const [entities, setEntities] = useState([]);
  const [customers, setCustomers] = useState([]);
  const [customerOptions, setCustomerOptions] = useState([]);
  const [form, setForm] = useState(defaultForm);
  const [showModal, setShowModal] = useState(false);
  const [isEdit, setIsEdit] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [selectedId, setSelectedId] = useState(null);

  const dataColumns = [
    { title: 'Name', name: 'name', searchable: true },
    { title: 'Customer', name: 'customers_text', searchable: false },
    { title: 'Type', name: 'type_display', searchable: false },
    { title: 'Status', name: 'status_display', searchable: false },
  ];

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setIsLoading(true);
      const res = await api.get('discount-plans');
      const data = res?.data;
      if (data?.status === 200 && Array.isArray(data?.data)) {
        setEntities(
          data.data.map((row) => ({
            id: row.id,
            name: row.name,
            type: row.type,
            type_display: row.type ? row.type.charAt(0).toUpperCase() + row.type.slice(1) : '—',
            is_active: !!row.is_active,
            status_display: row.is_active ? 'Active' : 'Inactive',
            customers: row.customers || [],
            customers_text: (row.customers || []).map((c) => c.name).join(', ') || '—',
          }))
        );
      }
    } catch (err) {
      msg.error(err?.response?.data?.message || 'Failed to load discount plans');
    } finally {
      setIsLoading(false);
    }
  };

  const fetchFormData = async () => {
    try {
      const res = await api.get('discount-plans/form-data');
      const data = res?.data;
      if (data?.status === 200 && data?.data?.customers) {
        const list = data.data.customers;
        setCustomers(list);
        setCustomerOptions(
          list.map((c) => ({
            value: c.id,
            label: `${c.name || ''} (${c.phone_number || ''})`,
          }))
        );
      }
    } catch (err) {
      msg.error(err?.response?.data?.message || 'Failed to load customers');
    }
  };

  const openNew = async () => {
    await fetchFormData();
    setForm({
      ...defaultForm,
      customer_id: [],
    });
    setSubmitted(false);
    setIsEdit(false);
    setSelectedId(null);
    setShowModal(true);
  };

  const hideDialog = () => {
    setShowModal(false);
    setForm(defaultForm);
    setSubmitted(false);
    setIsEdit(false);
    setSelectedId(null);
  };

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value,
    }));
    if (name === 'type' && value === 'generic') {
      setForm((prev) => ({
        ...prev,
        [name]: value,
        customer_id: customerOptions.map((o) => o.value),
      }));
    }
  };

  const handleCustomerChange = (selected) => {
    const selectedValues = selected ? selected.map((s) => s.value) : [];
    setForm((prev) => ({ ...prev, customer_id: selectedValues }));
  };

  const editRow = async (row) => {
    try {
      const [formRes, planRes] = await Promise.all([
        api.get('discount-plans/form-data'),
        api.get(`discount-plans/${row.id}`),
      ]);
      const plan = planRes?.data?.data;
      const formData = formRes?.data?.data;
      if (!plan) {
        msg.error('Plan not found');
        return;
      }
      const custList = formData?.customers || [];
      const options = custList.map((c) => ({
        value: c.id,
        label: `${c.name || ''} (${c.phone_number || ''})`,
      }));
      setCustomers(custList);
      setCustomerOptions(options);
      const planCustomerIds = (plan.customers || []).map((c) => c.id);
      const allIds = options.map((o) => o.value);
      const isGeneric = plan.type === 'generic';
      setForm({
        name: plan.name || '',
        type: plan.type || 'limited',
        customer_id: isGeneric ? allIds : planCustomerIds,
        is_active: !!plan.is_active,
      });
      setSelectedId(row.id);
      setIsEdit(true);
      setSubmitted(false);
      setShowModal(true);
    } catch (err) {
      msg.error(err?.response?.data?.message || 'Failed to load plan');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitted(true);
    if (!form.name?.trim()) {
      msg.error('Name is required');
      return;
    }
    if (!form.customer_id?.length) {
      msg.error('Select at least one customer');
      return;
    }

    const payload = {
      name: form.name.trim(),
      type: form.type,
      customer_id: form.customer_id,
      is_active: form.is_active,
    };

    try {
      if (isEdit && selectedId) {
        const res = await api.post('discount-plans/' + selectedId).values(payload);
        const data = res?.data;
        if (res?.status === 200 && data?.status === 200) {
          msg.success(data?.message || 'Discount plan updated');
          hideDialog();
          fetchData();
        } else {
          msg.error(data?.message || res?.error || 'Update failed');
        }
      } else {
        const res = await api.post('discount-plans').values(payload);
        const data = res?.data;
        if (res?.status === 200 && data?.status === 200) {
          msg.success(data?.message || 'Discount plan created');
          hideDialog();
          fetchData();
        } else {
          msg.error(data?.message || res?.error || 'Create failed');
        }
      }
    } catch (err) {
      msg.error(err?.response?.data?.message || 'Failed to save');
    }
  };

  const selectedCustomerOptions = customerOptions.filter((o) => form.customer_id.includes(o.value));

  return (
    <div>
      <h5 className="text-center">{moduleName}</h5>
      <br />
      <div className="row">
        <div className="col-sm-2">
          <SystemButton type="add-new" method={openNew} showText btnText="Create Discount Plan" />
        </div>
      </div>

      <FormModal
        moduleName={isEdit ? 'Update Discount Plan' : 'Create Discount Plan'}
        modalState={showModal}
        toggleFormModal={hideDialog}
        width="560px"
      >
        <form onSubmit={handleSubmit}>
          <div className="modal-body text-left">
            <p className="small text-muted">Fields marked with * are required.</p>
            <div className="form-group">
              <label>Name <span className="text-danger">*</span></label>
              <input
                type="text"
                name="name"
                className={`form-control ${submitted && !form.name?.trim() ? 'is-invalid' : ''}`}
                value={form.name}
                onChange={handleChange}
              />
            </div>
            <div className="form-group">
              <label>Customer <span className="text-danger">*</span></label>
              <Select
                isMulti
                closeMenuOnSelect={false}
                options={customerOptions}
                value={selectedCustomerOptions}
                onChange={handleCustomerChange}
                className="basic-multi-select"
                classNamePrefix="select"
                placeholder="Select customer..."
              />
              {form.type === 'generic' && (
                <small className="text-muted">Generic type: all active customers are included.</small>
              )}
            </div>
            <div className="form-group">
              <label>Type <span className="text-danger">*</span></label>
              <select
                name="type"
                id="type-select"
                className="form-control"
                value={form.type}
                onChange={handleChange}
              >
                {TYPE_OPTIONS.map((o) => (
                  <option key={o.value} value={o.value}>{o.label}</option>
                ))}
              </select>
              <small className="text-muted">Generic = apply to all customers; Limited = selected customers only.</small>
            </div>
            <div className="form-group form-check">
              <input
                type="checkbox"
                name="is_active"
                id="is_active"
                className="form-check-input"
                checked={form.is_active}
                onChange={handleChange}
              />
              <label className="form-check-label" htmlFor="is_active">Active</label>
            </div>
          </div>
          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" onClick={hideDialog}>
              <SafeFontAwesomeIcon icon={faTimes} className="mr-2" size="sm" />
              Cancel
            </button>
            <button type="submit" className="btn btn-primary">
              <SafeFontAwesomeIcon icon={isEdit ? faCheck : faPlus} className="mr-2" size="sm" />
              Submit
            </button>
          </div>
        </form>
      </FormModal>

      <br />
      <ListView
        columns={dataColumns}
        rows={entities}
        edit={editRow}
        loadingState={isLoading}
        searchAndFetch={() => fetchData()}
        actionsColumn
        showEditButton
        showDeleteButton={false}
        resetSearch={() => fetchData()}
        rowKey="id"
      />
    </div>
  );
};

export default DiscountPlan;
