// pos-client/src/views/pages/settings/discount.vue
<script setup>
import api from '@/service/api';
import { useToast } from 'primevue/usetoast';
import { onMounted, ref, watch } from 'vue';
import { useRouter } from 'vue-router';

const toast = useToast();
const router = useRouter();
const discounts = ref([]);
const discountPlans = ref([]);
const discountDialog = ref(false);
const discount = ref({
    name: '',
    discount_plan_id: [],
    applicable_for: 'All',
    is_active: true,
    product_list: [],
    productCodeInput: '',
    valid_from: null,
    valid_till: null,
    type: 'percentage',
    value: 0,
    minimum_qty: 1,
    maximum_qty: 999999,
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
});
const productRows = ref([]);
const submitted = ref(false);
const loading = ref(false);
const isEdit = ref(false);

const DAY_OPTIONS = [
    { value: 'Mon', label: 'Monday' },
    { value: 'Tue', label: 'Tuesday' },
    { value: 'Wed', label: 'Wednesday' },
    { value: 'Thu', label: 'Thursday' },
    { value: 'Fri', label: 'Friday' },
    { value: 'Sat', label: 'Saturday' },
    { value: 'Sun', label: 'Sunday' },
];

onMounted(() => {
    fetchDiscounts();
    fetchFormData();
});

async function fetchDiscounts() {
    try {
        const res = await api.get('discounts');
        if (res.data?.status === 200) {
            discounts.value = res.data.data || [];
        } else if (res.error) {
            toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to load discounts', life: 3000 });
        }
    } catch (e) {
        toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to load discounts', life: 3000 });
    }
}

async function fetchFormData() {
    try {
        const res = await api.get('discounts/form-data');
        if (res.data?.status === 200 && res.data.data?.discount_plans) {
            discountPlans.value = res.data.data.discount_plans;
        }
    } catch (e) {
        toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to load form data', life: 3000 });
    }
}

const discountPlanOptions = () =>
    discountPlans.value.map((p) => ({ label: p.name, value: p.id }));

function openNew() {
    discount.value = {
        name: '',
        discount_plan_id: [],
        applicable_for: 'All',
        is_active: true,
        product_list: [],
        productCodeInput: '',
        valid_from: new Date(),
        valid_till: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        type: 'percentage',
        value: 0,
        minimum_qty: 1,
        maximum_qty: 999999,
        days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    };
    productRows.value = [];
    submitted.value = false;
    isEdit.value = false;
    discountDialog.value = true;
}

async function editDiscount(d) {
    try {
        const res = await api.get(`discounts/${d.id}`);
        if (res.data?.status === 200 && res.data.data) {
            const data = res.data.data;
            discount.value = {
                id: data.id,
                name: data.name,
                discount_plan_id: data.discount_plan_ids || data.discount_plan_id || [],
                applicable_for: data.applicable_for || 'All',
                is_active: data.is_active !== false,
                product_list: data.product_list ? data.product_list.toString().split(',').filter(Boolean) : [],
                productCodeInput: '',
                valid_from: data.valid_from ? new Date(data.valid_from) : new Date(),
                valid_till: data.valid_till ? new Date(data.valid_till) : new Date(),
                type: data.type || 'percentage',
                value: parseFloat(data.value) || 0,
                minimum_qty: data.minimum_qty ?? 1,
                maximum_qty: data.maximum_qty ?? 999999,
                days: data.days_array || ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            };
            productRows.value = data.product_details || [];
            isEdit.value = true;
            discountDialog.value = true;
        }
    } catch (e) {
        toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to load discount', life: 3000 });
    }
}

watch(
    () => discount.value.applicable_for,
    (val) => {
        if (val === 'All') {
            productRows.value = [];
            discount.value.product_list = [];
        }
    }
);

async function addProductByCode() {
    const input = (discount.value.productCodeInput || '').trim();
    if (!input) return;
    const codes = input.split(',').map((c) => c.trim()).filter(Boolean);
    for (const code of codes) {
        if (productRows.value.some((p) => p.code === code)) {
            toast.add({ severity: 'warn', summary: 'Duplicate', detail: `Product ${code} already in list`, life: 2000 });
            continue;
        }
        try {
            const res = await api.get(`discounts/product-search/${encodeURIComponent(code)}`);
            if (res.data?.status === 200 && res.data.data) {
                const p = res.data.data;
                productRows.value.push({ id: p.id, name: p.name, code: p.code });
                discount.value.product_list = productRows.value.map((r) => r.id);
            } else {
                toast.add({ severity: 'error', summary: 'Not found', detail: `Product with code "${code}" not found`, life: 2000 });
            }
        } catch (e) {
            toast.add({ severity: 'error', summary: 'Error', detail: `Failed to find product "${code}"`, life: 2000 });
        }
    }
    discount.value.productCodeInput = '';
}

function removeProduct(index) {
    productRows.value.splice(index, 1);
    discount.value.product_list = productRows.value.map((r) => r.id);
}

function toggleDay(day) {
    const arr = discount.value.days || [];
    const i = arr.indexOf(day);
    if (i >= 0) arr.splice(i, 1);
    else arr.push(day);
    discount.value.days = [...arr];
}

function isDayChecked(day) {
    return (discount.value.days || []).includes(day);
}

function hideDialog() {
    discountDialog.value = false;
    discount.value = {};
    productRows.value = [];
}

function planNames(item) {
    const plans = item.discount_plans || [];
    return plans.length ? plans.map((p) => p.name).join(', ') : '—';
}

function validityDisplay(item) {
    const from = item.valid_from_formatted || (item.valid_from ? new Date(item.valid_from).toLocaleDateString() : '');
    const till = item.valid_till_formatted || (item.valid_till ? new Date(item.valid_till).toLocaleDateString() : '');
    return from && till ? `${from} - ${till}` : '—';
}

async function save() {
    submitted.value = true;
    if (!discount.value?.name?.trim()) {
        toast.add({ severity: 'error', summary: 'Validation', detail: 'Name is required', life: 3000 });
        return;
    }
    if (!discount.value.discount_plan_id?.length) {
        toast.add({ severity: 'error', summary: 'Validation', detail: 'Select at least one discount plan', life: 3000 });
        return;
    }
    if (discount.value.applicable_for === 'Specific' && !productRows.value.length) {
        toast.add({ severity: 'error', summary: 'Validation', detail: 'Add at least one product for Specific', life: 3000 });
        return;
    }
    if (!discount.value.days?.length) {
        toast.add({ severity: 'error', summary: 'Validation', detail: 'Select at least one day', life: 3000 });
        return;
    }
    loading.value = true;
    try {
        const payload = {
            name: discount.value.name.trim(),
            discount_plan_id: discount.value.discount_plan_id,
            applicable_for: discount.value.applicable_for,
            is_active: discount.value.is_active,
            valid_from: discount.value.valid_from ? new Date(discount.value.valid_from).toISOString().slice(0, 10) : null,
            valid_till: discount.value.valid_till ? new Date(discount.value.valid_till).toISOString().slice(0, 10) : null,
            type: discount.value.type,
            value: parseFloat(discount.value.value) || 0,
            minimum_qty: parseInt(discount.value.minimum_qty, 10) || 1,
            maximum_qty: parseInt(discount.value.maximum_qty, 10) || 999999,
            days: discount.value.days,
            product_list: discount.value.applicable_for === 'Specific' ? productRows.value.map((r) => r.id) : [],
        };
        if (isEdit.value && discount.value.id) {
            const res = await api.post(`discounts/${discount.value.id}`, payload);
            if (res.data?.status === 200) {
                toast.add({ severity: 'success', summary: 'Success', detail: res.data.message, life: 3000 });
                await fetchDiscounts();
                hideDialog();
            } else {
                toast.add({ severity: 'error', summary: 'Error', detail: res.data?.message || 'Failed to update', life: 3000 });
            }
        } else {
            const res = await api.post('discounts', payload);
            if (res.data?.status === 200) {
                toast.add({ severity: 'success', summary: 'Success', detail: res.data.message, life: 3000 });
                await fetchDiscounts();
                hideDialog();
            } else {
                toast.add({ severity: 'error', summary: 'Error', detail: res.data?.message || 'Failed to create', life: 3000 });
            }
        }
    } catch (e) {
        const msg = e.response?.data?.message || 'Failed to save discount';
        toast.add({ severity: 'error', summary: 'Error', detail: typeof msg === 'object' ? JSON.stringify(msg) : msg, life: 3000 });
    } finally {
        loading.value = false;
    }
}

function goToDiscountPlan() {
    router.push({ name: 'discount-plan' });
}
</script>

<template>
    <div class="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-950 p-4 md:p-6 lg:p-8">
        <div class="mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
                <h1 class="text-3xl font-bold text-gray-900 dark:text-gray-100 flex items-center gap-3">
                    <i class="pi pi-tag text-primary"></i>
                    Discount
                </h1>
                <p class="text-gray-600 dark:text-gray-400 mt-1">Manage discounts and validity</p>
            </div>
            <div class="flex gap-2">
                <Button label="Discount Plan" icon="pi pi-percentage" severity="secondary" outlined @click="goToDiscountPlan" />
                <Button label="Create Discount" icon="pi pi-plus" @click="openNew" />
            </div>
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700 overflow-hidden">
            <DataTable :value="discounts" stripedRows class="p-datatable-sm" scrollable>
                <template #empty>
                    <div class="text-center py-12 text-gray-500">No discounts found</div>
                </template>
                <Column field="id" header="#" style="width: 50px">
                    <template #body="slot">{{ slot.index + 1 }}</template>
                </Column>
                <Column field="name" header="Name" sortable style="min-width: 120px" />
                <Column field="value" header="Value" style="min-width: 90px">
                    <template #body="slot">{{ slot.data.value }} ({{ slot.data.type || 'percentage' }})</template>
                </Column>
                <Column header="Discount Plan" style="min-width: 140px">
                    <template #body="slot">{{ planNames(slot.data) }}</template>
                </Column>
                <Column header="Validity" style="min-width: 160px">
                    <template #body="slot">{{ validityDisplay(slot.data) }}</template>
                </Column>
                <Column field="days" header="Days" style="min-width: 80px">
                    <template #body="slot">{{ (slot.data.days || '').split(',').length }} days</template>
                </Column>
                <Column header="Products" style="min-width: 120px">
                    <template #body="slot">
                        {{ slot.data.applicable_for === 'Specific' ? (slot.data.product_list || '').toString().split(',').length + ' products' : 'All Products' }}
                    </template>
                </Column>
                <Column header="Status" style="min-width: 90px">
                    <template #body="slot">
                        <Tag :value="slot.data.is_active ? 'Active' : 'Inactive'" :severity="slot.data.is_active ? 'success' : 'secondary'" />
                    </template>
                </Column>
                <Column header="Action" style="width: 100px">
                    <template #body="slot">
                        <Button icon="pi pi-pencil" size="small" outlined severity="info" v-tooltip="'Edit'" @click="editDiscount(slot.data)" />
                    </template>
                </Column>
            </DataTable>
        </div>

        <Dialog v-model:visible="discountDialog" :style="{ width: '700px' }" :header="isEdit ? 'Update Discount' : 'Create Discount'" :modal="true" :dismissableMask="true" class="max-h-[90vh] overflow-y-auto">
            <p class="text-sm italic text-gray-500 mb-4">The field labels marked with <span class="text-red-500">*</span> are required input fields.</p>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                    <label class="block text-sm font-semibold mb-2">Name <span class="text-red-500">*</span></label>
                    <InputText v-model="discount.name" placeholder="Discount name" class="w-full" :invalid="submitted && !discount.name" />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Discount Plan <span class="text-red-500">*</span></label>
                    <MultiSelect
                        v-model="discount.discount_plan_id"
                        :options="discountPlanOptions()"
                        optionLabel="label"
                        optionValue="value"
                        placeholder="Select discount plans..."
                        filter
                        class="w-full"
                        :invalid="submitted && !discount.discount_plan_id?.length"
                    />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Applicable For <span class="text-red-500">*</span></label>
                    <Select
                        v-model="discount.applicable_for"
                        :options="[{ label: 'All Products', value: 'All' }, { label: 'Specific Products', value: 'Specific' }]"
                        optionLabel="label"
                        optionValue="value"
                        class="w-full"
                    />
                </div>
                <div class="flex items-center gap-2 md:col-span-2">
                    <Checkbox v-model="discount.is_active" :binary="true" inputId="disc-active" />
                    <label for="disc-active" class="cursor-pointer">Active</label>
                </div>
            </div>

            <div v-show="discount.applicable_for === 'Specific'" class="mt-4 space-y-2">
                <label class="block text-sm font-semibold">Select Product</label>
                <div class="flex gap-2">
                    <InputText
                        v-model="discount.productCodeInput"
                        placeholder="Type product code, comma separated"
                        class="flex-1"
                        @keydown.enter.prevent="addProductByCode"
                    />
                    <Button label="Add" icon="pi pi-plus" @click="addProductByCode" />
                </div>
                <div v-if="productRows.length" class="border rounded p-2 max-h-32 overflow-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b">
                                <th class="text-left py-1">#</th>
                                <th class="text-left py-1">Name</th>
                                <th class="text-left py-1">Code</th>
                                <th class="w-10"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="(row, idx) in productRows" :key="row.id" class="border-b">
                                <td class="py-1">{{ idx + 1 }}</td>
                                <td>{{ row.name }}</td>
                                <td>{{ row.code }}</td>
                                <td>
                                    <Button icon="pi pi-trash" text severity="danger" size="small" @click="removeProduct(idx)" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4">
                <div>
                    <label class="block text-sm font-semibold mb-2">Valid From <span class="text-red-500">*</span></label>
                    <Calendar v-model="discount.valid_from" dateFormat="dd-mm-yy" class="w-full" showIcon />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Valid Till <span class="text-red-500">*</span></label>
                    <Calendar v-model="discount.valid_till" dateFormat="dd-mm-yy" class="w-full" showIcon :minDate="discount.valid_from" />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Discount Type <span class="text-red-500">*</span></label>
                    <Select
                        v-model="discount.type"
                        :options="[{ label: 'Percentage (%)', value: 'percentage' }, { label: 'Flat', value: 'flat' }]"
                        optionLabel="label"
                        optionValue="value"
                        class="w-full"
                    />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Value <span class="text-red-500">*</span></label>
                    <InputNumber v-model="discount.value" :min="0" :maxFractionDigits="2" class="w-full" />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Minimum Qty <span class="text-red-500">*</span></label>
                    <InputNumber v-model="discount.minimum_qty" :min="0" :minFractionDigits="0" class="w-full" />
                </div>
                <div>
                    <label class="block text-sm font-semibold mb-2">Maximum Qty <span class="text-red-500">*</span></label>
                    <InputNumber v-model="discount.maximum_qty" :min="0" :minFractionDigits="0" class="w-full" />
                </div>
            </div>

            <div class="mt-4">
                <label class="block text-sm font-semibold mb-2">Valid on the following days</label>
                <div class="flex flex-wrap gap-4">
                    <div v-for="opt in DAY_OPTIONS" :key="opt.value" class="flex items-center gap-2">
                        <Checkbox :modelValue="isDayChecked(opt.value)" :binary="true" :inputId="'day-' + opt.value" @update:modelValue="toggleDay(opt.value)" />
                        <label :for="'day-' + opt.value" class="cursor-pointer">{{ opt.label }}</label>
                    </div>
                </div>
            </div>

            <template #footer>
                <Button label="Cancel" icon="pi pi-times" outlined @click="hideDialog" />
                <Button :label="isEdit ? 'Update' : 'Submit'" icon="pi pi-check" :loading="loading" @click="save" />
            </template>
        </Dialog>
    </div>
</template>

// pos-client/src/views/master/Discount.jsx
import React, { useState, useEffect } from 'react';
import { faTimes, faPlus, faCheck, faTrash } from '@fortawesome/free-solid-svg-icons';
import Select from 'react-select';
import { api, msg } from '../../services';
import { FormModal, ListView, SystemButton, SafeFontAwesomeIcon } from '../../components';

const moduleName = 'Discount';

const APPLICABLE_OPTIONS = [
  { value: 'All', label: 'All Products' },
  { value: 'Specific', label: 'Specific Products' },
];

const TYPE_OPTIONS = [
  { value: 'percentage', label: 'Percentage (%)' },
  { value: 'flat', label: 'Flat' },
];

const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const DAY_LABELS = { Mon: 'Monday', Tue: 'Tuesday', Wed: 'Wednesday', Thu: 'Thursday', Fri: 'Friday', Sat: 'Saturday', Sun: 'Sunday' };

const defaultForm = {
  name: '',
  discount_plan_id: [],
  applicable_for: 'All',
  is_active: true,
  valid_from: '',
  valid_till: '',
  type: 'percentage',
  value: '',
  minimum_qty: '0',
  maximum_qty: '0',
  days: [...DAYS],
};

const Discount = () => {
  const [entities, setEntities] = useState([]);
  const [discountPlanOptions, setDiscountPlanOptions] = useState([]);
  const [form, setForm] = useState(defaultForm);
  const [productList, setProductList] = useState([]);
  const [productCodeInput, setProductCodeInput] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [isEdit, setIsEdit] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [selectedId, setSelectedId] = useState(null);

  const dataColumns = [
    { title: 'Name', name: 'name', searchable: true },
    { title: 'Value', name: 'value_display', searchable: false },
    { title: 'Discount Plan', name: 'plans_text', searchable: false },
    { title: 'Validity', name: 'validity_text', searchable: false },
    { title: 'Days', name: 'days', searchable: false },
    { title: 'Products', name: 'products_text', searchable: false },
    { title: 'Status', name: 'status_display', searchable: false },
  ];

  const isSpecific = form.applicable_for === 'Specific';

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setIsLoading(true);
      const res = await api.get('discounts');
      const data = res?.data;
      if (data?.status === 200 && Array.isArray(data?.data)) {
        setEntities(
          data.data.map((row) => ({
            id: row.id,
            name: row.name,
            value: row.value,
            type: row.type,
            value_display: `${row.value} (${row.type || ''})`,
            discount_plans: row.discount_plans || [],
            plans_text: (row.discount_plans || []).map((p) => p.name).join(', ') || '—',
            valid_from: row.valid_from_formatted || row.valid_from,
            valid_till: row.valid_till_formatted || row.valid_till,
            validity_text: [row.valid_from_formatted, row.valid_till_formatted].filter(Boolean).join(' - ') || '—',
            days: row.days || '—',
            product_list: row.product_list,
            products_text: row.products_text || (row.product_list ? 'Specific' : 'All Products'),
            is_active: !!row.is_active,
            status_display: row.is_active ? 'Active' : 'Inactive',
          }))
        );
      }
    } catch (err) {
      msg.error(err?.response?.data?.message || 'Failed to load discounts');
    } finally {
      setIsLoading(false);
    }
  };

  const fetchFormData = async () => {
    try {
      const res = await api.get('discounts/form-data');
      const data = res?.data?.data;
      if (data?.discount_plans) {
        setDiscountPlanOptions(
          data.discount_plans.map((p) => ({ value: p.id, label: p.name }))
        );
      }
    } catch (err) {
      msg.error(err?.response?.data?.message || 'Failed to load form data');
    }
  };

  const openNew = async () => {
    await fetchFormData();
    const today = new Date().toISOString().slice(0, 10);
    setForm({
      ...defaultForm,
      valid_from: today,
      valid_till: today,
      days: [...DAYS],
    });
    setProductList([]);
    setProductCodeInput('');
    setSubmitted(false);
    setIsEdit(false);
    setSelectedId(null);
    setShowModal(true);
  };

  const hideDialog = () => {
    setShowModal(false);
    setForm(defaultForm);
    setProductList([]);
    setSubmitted(false);
    setIsEdit(false);
    setSelectedId(null);
  };

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? (checked ? [...prev.days, value].sort() : prev.days.filter((d) => d !== value)) : value,
    }));
  };

  const handlePlanChange = (selected) => {
    setForm((prev) => ({
      ...prev,
      discount_plan_id: selected ? selected.map((s) => s.value) : [],
    }));
  };

  const handleDayChange = (day, checked) => {
    setForm((prev) => ({
      ...prev,
      days: checked ? [...prev.days, day].sort() : prev.days.filter((d) => d !== day),
    }));
  };

  const searchProductAndAdd = async (code) => {
    const trimmed = (code || productCodeInput || '').trim();
    if (!trimmed) return;
    if (productList.some((p) => String(p.code).toLowerCase() === trimmed.toLowerCase())) {
      msg.warning('Product already in list');
      setProductCodeInput('');
      return;
    }
    try {
      const res = await api.get('discounts/product-search/' + encodeURIComponent(trimmed));
      const data = res?.data?.data;
      if (res?.status === 200 && data) {
        setProductList((prev) => [...prev, { id: data.id, name: data.name, code: data.code }]);
        setProductCodeInput('');
      } else {
        msg.error('Product not found');
      }
    } catch (err) {
      msg.error(err?.response?.data?.message || 'Product not found');
    }
  };

  const onProductCodeKeyDown = (e) => {
    if (e.key === ',' || e.key === 'Enter') {
      e.preventDefault();
      const val = productCodeInput.trim();
      if (val) searchProductAndAdd(val);
    }
  };

  const removeProduct = (index) => {
    setProductList((prev) => prev.filter((_, i) => i !== index));
  };

  const editRow = async (row) => {
    try {
      await fetchFormData();
      const res = await api.get('discounts/' + row.id);
      const d = res?.data?.data;
      if (!d) {
        msg.error('Discount not found');
        return;
      }
      const planIds = d.discount_plan_ids || (d.discount_plans || []).map((p) => p.id);
      const daysArr = d.days_array || (d.days ? d.days.split(',') : []);
      const products = d.product_details || [];
      setForm({
        name: d.name || '',
        discount_plan_id: planIds,
        applicable_for: d.applicable_for || 'All',
        is_active: !!d.is_active,
        valid_from: d.valid_from ? d.valid_from.slice(0, 10) : '',
        valid_till: d.valid_till ? d.valid_till.slice(0, 10) : '',
        type: d.type || 'percentage',
        value: String(d.value ?? ''),
        minimum_qty: String(d.minimum_qty ?? 0),
        maximum_qty: String(d.maximum_qty ?? 0),
        days: daysArr.length ? daysArr : [...DAYS],
      });
      setProductList(products);
      setProductCodeInput('');
      setSelectedId(row.id);
      setIsEdit(true);
      setSubmitted(false);
      setShowModal(true);
    } catch (err) {
      msg.error(err?.response?.data?.message || 'Failed to load discount');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitted(true);
    if (!form.name?.trim()) {
      msg.error('Name is required');
      return;
    }
    if (!form.discount_plan_id?.length) {
      msg.error('Select at least one discount plan');
      return;
    }
    if (!form.valid_from || !form.valid_till) {
      msg.error('Valid From and Valid Till are required');
      return;
    }
    if (form.value === '' || form.value === null || form.value === undefined) {
      msg.error('Value is required');
      return;
    }
    if (!form.days?.length) {
      msg.error('Select at least one day');
      return;
    }
    if (isSpecific && !productList.length) {
      msg.error('Add at least one product for Specific');
      return;
    }

    const payload = {
      name: form.name.trim(),
      discount_plan_id: form.discount_plan_id,
      applicable_for: form.applicable_for,
      is_active: form.is_active,
      valid_from: form.valid_from,
      valid_till: form.valid_till,
      type: form.type,
      value: parseFloat(form.value) || 0,
      minimum_qty: parseInt(form.minimum_qty, 10) || 0,
      maximum_qty: parseInt(form.maximum_qty, 10) || 0,
      days: form.days,
      product_list: isSpecific ? productList.map((p) => p.id) : [],
    };

    try {
      if (isEdit && selectedId) {
        const res = await api.post('discounts/' + selectedId).values(payload);
        const data = res?.data;
        if (res?.status === 200 && data?.status === 200) {
          msg.success(data?.message || 'Discount updated');
          hideDialog();
          fetchData();
        } else {
          msg.error(data?.message || res?.error || 'Update failed');
        }
      } else {
        const res = await api.post('discounts').values(payload);
        const data = res?.data;
        if (res?.status === 200 && data?.status === 200) {
          msg.success(data?.message || 'Discount created');
          hideDialog();
          fetchData();
        } else {
          msg.error(data?.message || res?.error || 'Create failed');
        }
      }
    } catch (err) {
      msg.error(err?.response?.data?.message || 'Failed to save');
    }
  };

  const selectedPlanOptions = discountPlanOptions.filter((o) => form.discount_plan_id.includes(o.value));

  return (
    <div>
      <h5 className="text-center">{moduleName}</h5>
      <br />
      <div className="row">
        <div className="col-sm-2">
          <SystemButton type="add-new" method={openNew} showText btnText="Create Discount" />
        </div>
      </div>

      <FormModal
        moduleName={isEdit ? 'Update Discount' : 'Create Discount'}
        modalState={showModal}
        toggleFormModal={hideDialog}
        width="95%"
      >
        <form onSubmit={handleSubmit}>
          <div className="modal-body text-left" style={{ maxHeight: '85vh', overflowY: 'auto' }}>
            <p className="small text-muted">Fields marked with * are required.</p>

            <div className="row">
              <div className="col-md-3 form-group">
                <label>Name <span className="text-danger">*</span></label>
                <input
                  type="text"
                  name="name"
                  className={`form-control ${submitted && !form.name?.trim() ? 'is-invalid' : ''}`}
                  value={form.name}
                  onChange={handleChange}
                />
              </div>
              <div className="col-md-3 form-group">
                <label>Discount Plan <span className="text-danger">*</span></label>
                <Select
                  isMulti
                  closeMenuOnSelect={false}
                  options={discountPlanOptions}
                  value={selectedPlanOptions}
                  onChange={handlePlanChange}
                  className="basic-multi-select"
                  classNamePrefix="select"
                  placeholder="Select discount plan..."
                />
              </div>
              <div className="col-md-3 form-group">
                <label>Applicable For <span className="text-danger">*</span></label>
                <select name="applicable_for" className="form-control" value={form.applicable_for} onChange={handleChange}>
                  {APPLICABLE_OPTIONS.map((o) => (
                    <option key={o.value} value={o.value}>{o.label}</option>
                  ))}
                </select>
              </div>
              <div className="col-md-3 form-group form-check mt-4">
                <input type="checkbox" name="is_active" id="is_active" className="form-check-input" checked={form.is_active} onChange={(e) => setForm((p) => ({ ...p, is_active: e.target.checked }))} />
                <label className="form-check-label" htmlFor="is_active">Active</label>
              </div>
            </div>

            {isSpecific && (
              <div className="row">
                <div className="col-md-9 form-group">
                  <label>Select Product <span className="text-danger">*</span></label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Type product code, then comma or Enter to add"
                    value={productCodeInput}
                    onChange={(e) => setProductCodeInput(e.target.value)}
                    onKeyDown={onProductCodeKeyDown}
                  />
                </div>
                <div className="col-12">
                  <table className="table table-sm table-bordered">
                    <thead><tr><th>#</th><th>Name</th><th>Code</th><th></th></tr></thead>
                    <tbody>
                      {productList.map((p, i) => (
                        <tr key={p.id}>
                          <td>{i + 1}</td>
                          <td>{p.name}</td>
                          <td>{p.code}</td>
                          <td>
                            <button type="button" className="btn btn-sm btn-danger" onClick={() => removeProduct(i)}>
                              <SafeFontAwesomeIcon icon={faTrash} size="xs" />
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            <div className="row">
              <div className="col-md-4 form-group">
                <label>Valid From <span className="text-danger">*</span></label>
                <input type="date" name="valid_from" className="form-control" value={form.valid_from} onChange={handleChange} required />
              </div>
              <div className="col-md-4 form-group">
                <label>Valid Till <span className="text-danger">*</span></label>
                <input type="date" name="valid_till" className="form-control" value={form.valid_till} onChange={handleChange} required />
              </div>
              <div className="col-md-4 form-group">
                <label>Discount Type <span className="text-danger">*</span></label>
                <select name="type" className="form-control" value={form.type} onChange={handleChange}>
                  {TYPE_OPTIONS.map((o) => (
                    <option key={o.value} value={o.value}>{o.label}</option>
                  ))}
                </select>
              </div>
              <div className="col-md-4 form-group">
                <label>Value <span className="text-danger">*</span></label>
                <input type="number" name="value" className="form-control" step="any" min={0} value={form.value} onChange={handleChange} required />
              </div>
              <div className="col-md-4 form-group">
                <label>Minimum Qty <span className="text-danger">*</span></label>
                <input type="number" name="minimum_qty" className="form-control" min={0} value={form.minimum_qty} onChange={handleChange} required />
              </div>
              <div className="col-md-4 form-group">
                <label>Maximum Qty <span className="text-danger">*</span></label>
                <input type="number" name="maximum_qty" className="form-control" min={0} value={form.maximum_qty} onChange={handleChange} required />
              </div>
            </div>

            <div className="row">
              <div className="col-md-6 form-group">
                <label>Valid on the following days</label>
                <ul className="list-unstyled">
                  {DAYS.map((day) => (
                    <li key={day}>
                      <label className="form-check-label">
                        <input
                          type="checkbox"
                          checked={form.days.includes(day)}
                          onChange={(e) => handleDayChange(day, e.target.checked)}
                        />
                        {' '}{DAY_LABELS[day]}
                      </label>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" onClick={hideDialog}>
              <SafeFontAwesomeIcon icon={faTimes} className="mr-2" size="sm" /> Cancel
            </button>
            <button type="submit" className="btn btn-primary">
              <SafeFontAwesomeIcon icon={isEdit ? faCheck : faPlus} className="mr-2" size="sm" /> Submit
            </button>
          </div>
        </form>
      </FormModal>

      <br />
      <ListView
        columns={dataColumns}
        rows={entities}
        edit={editRow}
        loadingState={isLoading}
        searchAndFetch={() => fetchData()}
        actionsColumn
        showEditButton
        showDeleteButton={false}
        resetSearch={() => fetchData()}
        rowKey="id"
      />
    </div>
  );
};

export default Discount;
